### ISSUE TITLE
DutyBuilderRegistration Re Broadcast Every Epoch 

### ISSUE THREAD

**Issue by ciaranmcveigh5** [ObolNetwork/charon#1009]
## Problem to be solved

Currently, for builder registration, Charon submits only one registration after boot.

When registrations are re-submitted at the start of every epoch from the VC clients charon notes that the duty has already been completed and therefore does not forward the request onto the beacon node.

After speaking with Teku we found out that the beacons are implemented to keep a local store of registrations and prune them after 3 epoch if a re-registration doesn't occur. This differs from the relays who (last time I check with flashbots) persist the registration permanently. 

When a validator isn't registered from teku's perspective it defaults to local block builds rather than builder network blocks

From Teku

"registered_validators will go back to empty on restart, that is why Teku registers all validators on startup
also there is expiry which is 3 epoch currently
so if you don't call register endpoint, then the validator registration will expire"

## Proposed solution

Re cast component to re broadcast the message to beacon

recast component:
 - it sits next to bcast 
 - so it subscribes to sigagg events, so get all aggregates signatures (same as bcast and aggsigdb) 
 - it stores the high slot DutyRegistration it receives (ignores other duties)
 - it also listens to epoch_events (need to add this functionality to scheduler to emit slot and epoch events)
 - resend DutyRegistration to broadcast on receipt of epoch event.
 
### Out of Scope

n/a

**Comment by corverroos** [comment]
Closing since done
