### ISSUE TITLE
Calculate beacon node score

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1030]
## Problem to be solved

We have some metrics that show how our beacon node is doing for example, app_eth2_latency. But there are other possibilities for a beacon node to not behave as expected.

## Proposed solution

Calculate beacon node score which will help our users to properly assess what is wrong with their beacon node. The score should be in between 0-5 with the following cases:

- Score 0: Beacon node is not connected or beacon node is down.
- Score 1: Beacon node is connected but syncing.
- Score 2: Beacon node is synced but has p90 latency of >1s.
- Score 3: Beacon node is synced but has p90 latency in between 500ms and 1s.
- Score 4: Beacon node is synced but has p90 latency in between 250ms and 500ms.
- Score 5: Beacon node is synced but has p90 latency of <250ms.

It should update the beacon score every 10s similar to what we have in `startReadyChecker`.
Expose prometheus gauge metric as `app_monitoring_beacon_score`.
Also  expose a montoringapi endpoint similar to readyz. The endpoint should be `/beacon-score`.

### Out of Scope

Add the corresponding to `compose` dashboard and `charon-distributed-validator-node` repo's dashboard.

**Comment by corverroos** [comment]
What about errors? And the fact that we can be connected to multiple beacon nodes, some of which might be syncing while others are not. And different endpoints have different latencies, e.g.`node_syncing` is much faster than `attester_data`.

Also I think the score should be out of 100, same as validator effectiveness
