### ISSUE TITLE
`charon dkg` can take a remote URI for a DKG cluster-definition

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1045]
## Problem to be solved

Copying a definition file to .charon always goes poorly in user testing. Designing the launchpad with this in mind might not be such a good idea. 

## Proposed solution

We already want to move away from a `--data-dir` flag to a `--definition-file` flag as per https://github.com/ObolNetwork/charon/issues/994

Allow specifying a URI to a remote definition file. (Oisin will get the develop.kyne.eu/ api endpoint running on an `api.obol.tech` domain so it looks pretty). 

### Out of Scope

Nothing to do with `charon run` or cluster-lock.json

**Comment by corverroos** [comment]
Note we already have a `--definition-file` flag. `--data-dir` is only used to load the `charon-enr-private-key`
