### ISSUE TITLE
Charon can aggregate

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1046]
## Problem to be solved

We have outlined a new endpoint for the beacon api [here](https://github.com/ethereum/beacon-APIs/pull/224). We want to prove this proposal will work before we lean heavily on client teams to implement it (particularly into their VC side, not their BN side)

## Proposed solution

Build this endpoint into our `validatorAPI`, and add the needed code to make this happen to `go-eth2-client`. 

Use either a forked vouch (or LH or Teku) to produce a valid aggregation on a goerli testnet. 

### Out of Scope

Having a prod-ready validator client that uses this endpoint, this can be an ugly hack fork that gets thrown away.

**Comment by corverroos** [comment]
Here is the design doc: https://docs.google.com/document/d/1_J8Y9M4FsONmEENSPwzzZW9n_zrnmAPGoSO2sm6DIO8/edit#
