### ISSUE TITLE
Create a `charon alpha test` command

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1048]
## Problem to be solved

To date we are on testnets not mainnet, so we can activate validators to test the efficacy of a cluster. Eventually however, people will be setting up DVs with the intention of activating them on mainnet. For this case, they probably don't want to spend a month activating a testnet validator and getting the hang of things, instead they would probably like something that takes <5 minutes that outputs a "report" not unlike a classic ping-test, but for whether this proposed cluster-lock is going to work well. 

## Proposed solution

Create a new command `charon alpha test` (Before we promote it to a `charon test` command once more final). It should:
- Read in a cluster-lock.json
- Attempt to establish connections with the peer ENRs 
- The process should retry indefinitely by default to connect, but maybe we should consider a timeout option
- [This is where things get a bit TBC, and is the purpose of this spike/alpha] Perform a variety of tests to infer prospective cluster health, these might include:
    - Can all nodes ping one another? What is their packet loss and RTT? Is our NAT open? Are we bootnode or direct connected to peers?
    - Can all nodes ping/performance/readiness test their beacon node? (this `test` command probably needs a `--beacon-node-endpoints` flag and other `charon run` flags to be a fair replication of `run`) What is its RTT? is(are) the BN returning 5XX or unexpected 4XXs? How many consensus client peers does it report? Is it synced? what version of what client is it? Is there a clock skew versus charon? (don't think we can calculate this) If we GET every public key in the lock file, what comes back for them from the BN? (e.g. validator status/balance)
    - Is validatorAPI being polled by a VC? Is it being polled for private keys contained in the cluster-lock? Are any private keys in the cluster-lock not being polled for? Does it have an event stream open?

After testing these three interfaces (BN, VC, Peers) print a comprehensive performance report to console that outlines A,B,C, scores for each aspect, and prints feedback about what can be improved, and whether we think this configuration will work well if activated. 

### Out of Scope

Not every test has to be implemented all in one go. So long as we have the command, the skeleton test framework, and maybe 1 test for each of the three interfaces working, if we create tickets for all of the remaining tests to completed, we can still close this ticket then as it meets our definition of done.

**Comment by corverroos** [comment]
`charon run` already does all these things. Maybe just a dedicated "test grafana dashboard" will suffice?

**Comment by gsora** [comment]
I'm giving some thought to this issue. 

> they would probably like something that takes <5 minutes that outputs a "report" not unlike a classic ping-test, but for whether this proposed cluster-lock is going to work well.

What do you mean? 

Working well as in "all peers are online and within a reasonable ping/latency"?

I'm struggling to find an appropriate scope for this functionality: why would a user run `test` instead of `dkg` or `run`?

**Comment by boulder225** [comment]
Closing it since has been converted into an epic, breaking it down into multiple tickets.
