### ISSUE TITLE
Add support for `DutyAggregator` to `parsigex`

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1095]
## Problem to be solved

Add support for `DutyAggregator` to `parsigex` component.

## Proposed solution

* Add a new switch case `case core.DutyAggregator:` in `core/parsigex/parsigex.go`
* Add signature verification support for `phase0.SignedAggregateAndProof` in `eth2util/signing/signing.go`

### Out of Scope

None

**Comment by dB2510** [comment]
closed by #1122
