### ISSUE TITLE
Handle feeRecipient gracefully

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1100]
# 🐞 Bug Report

### Description

It's not clear we use the `feeRecipient` field barely at all bar MEV-boost registration. We should assert that we use it properly from the cluster-lock and nowhere else. 

### Has this worked before in a previous version?

No

## 🌍  Your Environment

**What version of Charon are you running? (Which release)**

v0.10

**Anything else relevant (validator index / public key)?**

## Solution

Log feeRecipient in charon run.

**Comment by OisinKyne** [comment]
Outstanding Qs:

- How do we override default validator set fee recipients
- Can we default feeRecipient to withdrawalAddress? 
- Can we enforce a single feeRecipient

**Comment by corverroos** [comment]
Similar to builder registrations, the beacon api has a `POST /eth/v1/validator/prepare_beacon_proposer` endpoint to provide your desired fee recipient for block proposal. See https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/prepareBeaconProposer. 

We should:
 - Call this endpoint with the lock file fee recipient
 - Ensure the correct fee recipient is received when fetching a block
