### ISSUE TITLE
Wire charon CI with the public bootnodes CD pipeline

### ISSUE THREAD

**Issue by eth2devops** [ObolNetwork/charon#1138]
## Problem to be solved
We need to automate bootnodes deployments whenever Charon image is published

## Proposed solution
Add a new job to the workflows/build-push-deploy.yml to trigger bootnode [pipeline: workflows/bootnodes-tf-apply.yaml](https://github.com/ObolNetwork/obol-infrastructure/actions/workflows/bootnodes-tf-apply.yaml)

**Comment by OisinKyne** [comment]
This was done I think @eth2devops ? Assume it can be closed with your name on it

**Comment by eth2devops** [comment]
@OisinKyne not yet.
