### ISSUE TITLE
Mock sync committee message flow

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1151]
## Problem to be solved

We are adding a new duty as `DutySyncCommitteeMessage` which should be responsible for submitting sync committee messages to beacon node. Before starting implementation for this duty, we need a mock flow in terms of tests to validate data types and interfaces involved.

## Proposed solution

- Add support for following interfaces to eth2wrap and beaconmock:
  - SyncCommitteeDutiesProvider
  - SyncCommitteeMessagesSubmitter
  - SyncCommitteesProvider
- Introduce a new duty as `DutySyncCommitteeMessage`.
- Add support in validatorapi to intercept following endpoints
   - [GET sync committee duties](https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/getSyncCommitteeDuties)
   - [POST sync committee messages](https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/submitPoolSyncCommitteeSignatures)
   - These endpoints should be empty methods which only returns mock data and/or nil error. 
- Add a new `core.SignedData` implementation that wraps `eth2/altair.SyncCommitteeMessage` as **SignedSyncCommitteeMessage**.
 - Add an empty switch case in `core.parsigex.NewEth2Verifier` corresponding to `DutySyncCommitteeMessage`.
 - Add support for `DutySyncCommitteeMessage` in bcast without implementation to not result in an error.
 - Add TODOs for adding implementations later wherever necessary.
 - Add an integration test in validatorapi wiring all the components. This test should pass with or without the implementation.

**Comment by corverroos** [comment]
See #1172
