### ISSUE TITLE
Spec Prysm support

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1190]
## Problem to be solved

We want to support all validator client implementations. 

## Proposed solution

Setup time with the prysm team to dig deep into their VC implementation. Understand what parts of their implementation mandate the use of grpc and access to the full ~50MB state object (via _debug methods only in HTTP). Write a design doc for what a `valdiatorgrpc` component would look like in charon. 

### Out of Scope

Implementing the proposal is not part of this ticket. This is just to get a first cut at a design doc after research with the prysm team and review by the Obol and prysm teams.

**Comment by corverroos** [comment]
Closing this as Prysm is going to add support for BeaconAPI
