### ISSUE TITLE
Upgrade EIP712 signature structure

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1203]
## Problem to be solved

The cluster definition EIP712 signature structure needs to be updated for improved UX in the DV Launchpad.

## Proposed solution

See this [design doc](https://docs.google.com/document/d/1lYP1IU56JLtadrdaZTA9J1edGJjEaG8hLesyQlNxjCc/edit#).

TL;DR:
 - Create two `PrimaryTypes` signatures, `ENR` and `ConfigHash`.
 - Only include `name=Obol`, `version=1`,`chainID=<charinID>` in the `EIP712Domain` structure.
 - Only include `config_hash=string(configHashHex)` in the ConfigHash message.
 - Only include `end=string(enrString)` in the ENR message.
 
 This is a breaking change ito signature verification. But since there are no actual signed lock files or definition files in the wild, we are deprecating support for older signatures versions.
 
 Since v1.3 is still in draft, add this as part of v1.3.
 Error when unmarshalling any older version (1.0-1.2) that contains signatures.
 Skip signature verification for older versions (1.0-1.2).

We need to document how these signatures are created since it is part of the cluster definition spec.
See if we can find examples of other spec of EIP712 signatures. Add that to the spec in the `configuration.md` file.
### Out of Scope

We need to release v1.3 at some point before v0.11 release.

**Comment by dB2510** [comment]
Closed with final PR #1234
