### ISSUE TITLE
Charon cannot start if any beacon node is down

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1312]
# 🐞 Bug Report

## Problem to solve

Charon cannot start if any of the configured beacon-node-endpoints are not responding. So even though some beacon nodes are up and available, charon cannot start if only a single of the BNs are down. 

This is due to go-eth2-client that fails to initialise if the BN is not accessible.

## Proposed Solution

Wrap go-eth2-client instances in a `LazyClient` type that tries to initialise the underlying client on each API call if not initialised yet.

**Comment by OisinKyne** [comment]
Is this long fixed? @corverroos

**Comment by corverroos** [comment]
this isn't fixed no
