### ISSUE TITLE
Cache validators by pubkey in eth2client

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1396]
## Problem to be solved

The eth2client endpoint with the highest call rate is `validators_by_pubkey`. We call that in most validator api endpoints. It is also pretty slow. But the data is pretty static, it only changes every epoch as new validators are activated and exited/slashed.

## Proposed solution

Add an eth2wrap option `WithEpochCache` that:
 - caches validators by pubkey
 - subscribes to scheduler events and clears the cache on new epochs

**Comment by corverroos** [comment]
See high call rate, high latency and warns/errors fetching validators by pubkey
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/29249923/200509779-d4d8f280-7245-4457-9d04-e8872264f30f.png">

**Comment by OisinKyne** [comment]
How heavy is this hitting our Obol Performance Cluster? @LukeHackett12

**Comment by LukeHackett12** [comment]
I haven't seen this request popping up in errors afaik, taking a deeper look now.

**Comment by OisinKyne** [comment]
![Image](https://user-images.githubusercontent.com/4981644/212060227-5b061d5f-6c2a-428f-8988-eaca9a55b723.png)

Looking at the performance cluster now, by far the heaviest request is `get_validator`, which, considering this is lighthouse whereas I guess corver's is teku, is probably the same functionality but lighthouse is querying by index and teku is asking by pub key. But this indicates that if we could cache stuff we could massively reduce our BN load at scale.

**Comment by LukeHackett12** [comment]
Ah OK sorry lacked a bit of context didn't know they were equivalent should have guessed.

**Comment by OisinKyne** [comment]
All good, np

**Comment by gsora** [comment]
I believe this was implemented in https://github.com/ObolNetwork/charon/pull/1397
