### ISSUE TITLE
Spike beacon-fuzz integration

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon#1422]
- Spike first

**Comment by xenowits** [comment]
https://github.com/sigp/beacon-fuzz

**Comment by xenowits** [comment]
The design document lives [here](https://docs.google.com/document/d/16tl8PpcTJF8i_ynUSuk0exDhl-xU5IA1Me_BE-GaPKA/edit?usp=sharing)

TL;DR: The tools present in the beacon-fuzz repo like _eth2diff_ and _beaconfuzz_v2_ are not relevant to our usecase. The major point being that - **Charon is a middleware client, not a consensus client**.
