### ISSUE TITLE
Add support for `capella` blocks

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1464]
## Problem to be solved

Ethereum is eyeing to introduce withdrawals in next upgrade (shanghai). This introduces new block version named `capella` which introduces some new fields to `BeaconBlockBody` and `ExecutionPayload`. For more details [refer](https://github.com/ethereum/consensus-specs/tree/dev/specs/capella).

## Proposed solution

- Add support for capella versioned beacon block wherever block version is considered across charon codebase.
- Add relevant tests.

**Comment by corverroos** [comment]
What is the timeline on this for goerli and gnosis? ie, by when does need to be in?

**Comment by dB2510** [comment]
> What is the timeline on this for goerli and gnosis? ie, by when does need to be in?

There is no announcement for specific date as when it will be live on goerli or gnosis, but client teams are under development currently. `go-eth2-client` has already added support.
We can track shanghai upgrade planning here: https://github.com/ethereum/pm/issues/450.
