### ISSUE TITLE
Go warning of deprecated flag

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1470]
# 🐞 Bug Report

### Description
Running `go install .` ends with 

```
# github.com/obolnetwork/charon
ld: warning: -no_pie is deprecated when targeting new OS versions
```
### Has this worked before in a previous version?

Probably if its a deprecation warning

## 🔬 Minimal Reproduction

`go install .`

## 🔥 Error

<pre><code>
# github.com/obolnetwork/charon
ld: warning: -no_pie is deprecated when targeting new OS versions

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
OSX
  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
  <code>
latest main
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by xenowits** [comment]
@OisinKyne what version of go are you running?

**Comment by xenowits** [comment]
Hey @OisinKyne , would it be cool to close this or move it to the parking lot until we have a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) ?
