### ISSUE TITLE
Write validator registration proposal doc

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1477]
## Problem to be solved

In order to support builder API we need to submit validator registration which involves validator public key in signing message. If VC submits a validator registration signed with its private key share then the signing message will contain partial public key. We need to propose an API similar to aggregations in order to support builder API with charon.

## Proposed solution

Write validator registrations doc and open a PR in https://github.com/ObolNetwork/beacon-APIs repo.
Note: We already have a PR open for this change by ciaran: https://github.com/ObolNetwork/beacon-APIs/pull/1.

**Comment by thomasheremans** [comment]
Out of scope: getting feedback

**Comment by thomasheremans** [comment]
@OisinKyne to review
