### ISSUE TITLE
Incorrect failed duty reason when deadline reached - tracker v2

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1478]
## Problem to be solved

Failed duty reasons doesn't support duties that expire (reach their deadline). It assumes something in the component errored, while it was the duty context. This results in correct but concerning logs, e.g.:

```
19:13:55.908 [35mDEBG[0m [32mvapi [0m Partial signed data stored {"count": 6, "pubkey": "b56_ec9", "duty": "6030218/attester", "vapi_endpoint": "submit_attestations"}
19:13:55.908 [35mDEBG[0m [32mparsigex [0m Partial signed data stored {"count": 7, "pubkey": "b56_ec9", "duty": "6030218/attester", "peer": "frantic-road"}
19:13:57.504 [35mDEBG[0m [32mparsigex [0m Threshold aggregated partial signatures {"duty": "6030218/attester", "peer": "lazy-room"}
19:13:57.507 [31mERRO[0m [32mparsigex [0m Subscribe error: context deadline exceeded {"duty": "6030218/attester", "peer": "lazy-room"}
19:14:20.003 [33mWARN[0m [32mtracker [0m Duty failed {"step": "sig_aggregation", "reason": "bug: threshold aggregation of partial signatures failed due to inconsistent signed data", "duty": "6030218/attester"}
```

## Proposed solution

Refactor tracker into tracker2 which will receive events by "wrapping component inputs" rather than "listening to component outputs".  This way if component returns any error then it can be captured and analysed by tracker2. Make sure to add some time duration to analyser and deleter of tracker2 so that it does not clash with duty expired events.

**Comment by corverroos** [comment]
Best way to do this is probably to refactor tracker events from being "listen to component outputs" to "wrapping component inputs" since then it can detect the errors that components return and check what error it is.

**Comment by thomasheremans** [comment]
Need to create further tickets
