### ISSUE TITLE
Cache fork schedule by epoch

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1479]
## Problem to be solved

Every time we need to verify any eth2 signed data, we fetch the fork schedule to calculate domain. This not only introduces big delays (if the BN is far), but it also introduces the risk of dropping partial signatures on any BN network issues or timeouts resulting in higher risk of failed duties.

The fork schedule is definitely static per epoch. So we can cache it without risks.

## Proposed solution

Follow the [reverted valcache](https://github.com/ObolNetwork/charon/pull/1405) implementation but for fork schedules.

**Comment by xenowits** [comment]
Closing this ticket as `go-eth2-client` already [caches](https://github.com/attestantio/go-eth2-client/blob/master/http/service.go#L47) information about [fork-schedule](https://github.com/attestantio/go-eth2-client/blob/master/http/forkschedule.go) and [spec](https://github.com/attestantio/go-eth2-client/blob/master/http/spec.go), so we don't need to.
