### ISSUE TITLE
Add --definition-file flag to create cluster command that downloads the partial definition and uses it.

### ISSUE THREAD

**Issue by HananINouman** [ObolNetwork/charon#1490]
## Problem to be solved

We want to use the solo flow in the launchpad.

## Proposed solution

We have a cluster definition format that supports creator only files, now we need to make this format pullable on the `create cluster` command. 

We should also refactor the outputs of the create cluster command to spit out a folder per node. 
/node0
/node1
/node2
/node3

Each folder should contain a .charon/ folder with the format ingestable by the CDVN repo

**Comment by thomasheremans** [comment]
Need to create separate ticket for the folder restructuring
