### ISSUE TITLE
Create a `--publish` flag on the `dkg` and `create cluster` commands that pushes the produced lockfile to the obol api

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1492]
## Problem to be solved

We want to give a status page to people that shows the health of a cluster. We are creating a resource in the obol api to store pubkeys and their associated details. https://github.com/ObolNetwork/obol-api/issues/13

## Proposed solution

Add an optional flag to 
- [ ] `charon dkg`
- [ ]  `charon create cluster`

Called `--publish` (open to counterproposals), that will push the signed lock file to the obol API. The dkg/create command shouldn't fail outright if this POST request fails, but it should log a `warn` to indicate that publishing failed and that a cluster status page would not be available. 

### In Scope

Updating the docs and the charon cli output to reflect this new flag
Consulting with legal to ensure we have waivers/explainers set up that allow us to record this information if they give it to us.

**Comment by corverroos** [comment]
Another alternative in a simple bash script in cdvn repo, `./publish_lock_file_to_obol.sh`:
 - Dedicated action that any single operator can perform
 - Nice dedicated to print waiver
 - No need to complicate and include in DKG. Less things to worry about during DKG.
 - Retry on failure is handled by user
 - Can be performed at any time, not limited to making the decision at DKG.

**Comment by Battenfield** [comment]
This `--publish` flag will help out with the UX tremendously as it requires no extra steps on the user's behalf.

Alternatively, we can also have a manual upload option in the launchpad, similar to the dkg. Where users can drag and drop their lock file.
