### ISSUE TITLE
Clock diff still includes connection opening delay

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1494]
## Problem to be solved

We tried to fix clock diff spikes in #1474 but it didn't work since it only fixes the RTT calculation. It doesn't fix the "sentAt" part of the calculation which still include connection opening delay. 

## Proposed solution

Instead of using `sentAt+rtt/2` to calculate expectedSentAt, use `now()-rtt/2`.

**Comment by xenowits** [comment]
Clock offset graph for the last 24 hours with the included changes:
<img width="1415" alt="Screenshot 2023-01-06 at 20 20 53" src="https://user-images.githubusercontent.com/43061995/211036413-94f38ef2-2bb8-45ab-95c7-e33cceb72f2a.png">
