### ISSUE TITLE
Test cluster with multiple dv nodes with same validator private keyshare

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1523]
## Problem to be solved

We haven't tested the scenario when two charon dv nodes run with the same validator private keyshare. For ex: what happens when a user runs a node at his home as well as on the cloud simultaneously with the same keyshare?

Charon's architecture is idempotent wrt partial signatures. Also, the major issue is libp2p authentication and connections and when we tested this scenario, one of the duplicates couldn't connect. But this is probably not consistent, so duplicate A can be connected to some nodes and duplicate B can be connected to some other nodes.

## Proposed solution

We should test and understand this scenario better. One possible method is to create a test in `compose` which runs two nodes with the same keys and we analyze the results.

### Out of Scope

None.

**Comment by corverroos** [comment]
I think starting with an adhoc test is fine, not sure compose is the right way to go.

**Comment by thomasheremans** [comment]
We'll need to document the outcome of such a a case and add to the FAQ docs
