### ISSUE TITLE
Extend inclusion delay logic to track failed attestation

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1538]
## Problem to be solved

To track cluster wide failed attestation, currently we need to use external tools like beaconcha.in or rated APIs. Every peer reports failed attestation from tracker component but that reporting is local to each peer. We need a method to track cluster wide failed attestation.

## Proposed solution

- Extend inclusion delay logic in order to track failed attestations.
- If an attestation isn't included in next 32 slots (1 epoch) then it should be marked as failed/missed. Refer: 
   - https://kb.beaconcha.in/attestation#attestation-scenarios 
   - https://www.youtube.com/watch?v=SPcgevcDqDE 
   - https://www.attestant.io/posts/defining-attestation-effectiveness/
- Add a counter metric: `core_tracker_failed_attestations_total`.
- Add a panel for the above metric to simnet overview dashboard.

**Comment by corverroos** [comment]
What should the initial delay be at startup before we can mark attestations as failed? Since charon only starts tracking blocks from startup (with a delay as well).

**Comment by thomasheremans** [comment]
First Design Doc
