### ISSUE TITLE
Instrument block sizes

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1543]
## Problem to be solved

We want better understanding of block proposal failure reasons. As a first step, we can instrument block sizes to gather data on how big or small beacon blocks are. This can help us reason better as to if block proposal fails due to bigger blocks.

## Proposed solution

Add a gauge (`BlockSizeGauge`) in `fetcher` component. Calculate block-size in KB and push metric when fetcher downloads a block from the beacon node.

To get a rough idea, please check the historical ethereum block sizes [here](https://etherscan.io/chart/blocksize).

### Out of Scope

None.

**Comment by corverroos** [comment]
this will only be populated once every couple months when we propose a block, not sure this is very useful in practice. And one can easily look at that link to get the answer

**Comment by corverroos** [comment]
Also not sure what actionable info this will provide, we already instrument p2p network usage, which is much more actionable and covers the same issue. Closing for now.
