### ISSUE TITLE
Capella backwards compatibility tests

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1587]
## Problem to be solved
We want to make sure charon is backwards compatible when we add support for new ethereum [forks](https://github.com/ethereum/consensus-specs#in-development-specifications), such as capella.

## Proposed solution
1. Write backwards compatibility tests for capella.
2. Add alerts if tests fail.

**Comment by thomasheremans** [comment]
Hey @xenowits could you add a size please, thanks!

**Comment by xenowits** [comment]
<img width="1733" alt="Screenshot 2023-01-09 at 15 39 32" src="https://user-images.githubusercontent.com/43061995/211284432-892012d3-e744-41ef-8fd8-a8bac91f39ff.png">
