### ISSUE TITLE
Kryptology replacement spike + design doc complete + tickets sized.

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1588]
## Problem to be solved

We need to replace kryptology with the alternative cryptography package to support threshold BLS cryptography in charon. This is because [kryptology](https://github.com/coinbase/kryptology) has been archived by coinbase. We need to write a design doc where all the alternatives needs to be analysed and compared.

## Proposed solution

Write a design doc to analyse and compare alternatives to replace our current cryptography package [kryptology](https://github.com/coinbase/kryptology). The alternatives that needs to be considered are:
- https://github.com/supranational/blst
- https://github.com/drand/kyber-bls12381
- https://github.com/herumi/bls-eth-go-binary

Create relevant tickets based on the design doc which will be taken by the team.

### Out of Scope

Implementation related to the design doc is out of scope of this ticket.

**Comment by corverroos** [comment]
where did you find the alternatives?

Suggest looking at what prysm and vouch uses.

**Comment by OisinKyne** [comment]
I'm intending for @gsora to take a look at this ticket, thought I made that apparent in backlog grooming. Intention is for him to get an understanding of the low level crypto libs and operations we currently use before looking at what else is out there.

**Comment by corverroos** [comment]
Alex Wade auditor suggests https://github.com/supranational/blst which "has been audited and everything" and funded by the EF.

**Comment by gsora** [comment]
This is the first draft document that outlines the research and considerations given to each mentioned library, along with a general proposal on what to do next: https://docs.google.com/document/d/1oh90q-QMitxIp0c-e8ZcLjhZTKvdU0OufRhxJqHhun8/edit#

**Comment by gsora** [comment]
Closing in favor of the next iteration of this process https://github.com/ObolNetwork/charon/issues/1658
