### ISSUE TITLE
Instrument beacon node peer count

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1603]
## Problem to be solved

It has been found that even if charon submits all the attestations to beacon node successfully, there are some cases where some of them doesn't get included in the beacon chain and this leads to missed attestations. This *might* be due to low peer count of beacon node.

![Screenshot 2023-01-09 at 11 40 43 AM](https://user-images.githubusercontent.com/37813203/211274732-b7baef75-3e4b-4c16-a571-7b222f67cb56.png)
![Screenshot 2023-01-09 at 11 40 52 AM](https://user-images.githubusercontent.com/37813203/211274737-64183f69-e503-4a49-8464-f2cfc88563fd.png)

## Proposed solution

We need to instrument beacon node peer count to correlate with missed duties. We can use [`/eth/v1/node/peer_count`](https://ethereum.github.io/beacon-APIs/#/Node/getPeerCount) to query peer count and instrument it in `app/monitoring.go` as `app_monitoring_beaconnode_peercount` gauge. Once we have more understanding of how it impacts attestation inclusion, we could then maybe incorporate it into beacon node score.

**Comment by xenowits** [comment]
<img width="926" alt="Screenshot 2023-01-25 at 22 22 09" src="https://user-images.githubusercontent.com/43061995/214628227-1f60df19-5b00-4c4f-a8ab-91532c41eb45.png">
