### ISSUE TITLE
Require fee_recipient in commands

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1613]
## Problem to be solved

Fee_recipient is optional in all commands: `create dkg`, `create cluster`, `dkg`.

This results in empty fee_recipient in charon run that results in warning logs:
```
Proposing block with unexpected fee recipient address {"expected": "", "actual": "0x0000000000000000000000000000000000000000", "duty": "4736088/proposer"}
```

## Proposed solution

Either make it non-optional, so check it isn't empty.

Or make it default to withdrawal address, but this is implicit log and require documentation and warnings and stuff which isn't great.

**Comment by OisinKyne** [comment]
Yeah lets not make a default nor should it be optional.

However if `--definition-file` is passed that overrides (all?) other flags, so its not needed then, but the definition-file should also assert that a fee_recipient is set. 

Open Q: How might this flag work if we tried to make it compatible with multiple withdrawal addresses and multiple fee recipients? 🤔  CC @dB2510 (out of scope of this ticket though)

**Comment by dB2510** [comment]
This is already done as part of #1756
