### ISSUE TITLE
Mark a proposal as failed in metrics if we broadcast it too late

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1638]
## Problem to be solved

In HCNS we broadcasted a block proposal at circa ~13.5s and our charon clients thought that was okay. In practice it was not and the proposal was missed.

## Proposed solution

Maybe just tighten the deadliner down to 1/3rd of a slot and mark failed sooner? 

### Out of Scope

If there is anything to highlight as out of scope for this issue, please outline it here.

**Comment by boulder225** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/1638?planning-poker) with Zenhub @boulder225

**Comment by corverroos** [comment]
Since we monitor onchain inclusion, this isn't required
