### ISSUE TITLE
Add new validator registration endpoint to beacon api spec

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1640]
## Problem to be solved

We need to add a new endpoint for validator registrations to the [beacon api spec](https://github.com/ObolNetwork/beacon-APIs). See [design doc](https://docs.google.com/document/d/1J9Kv2LNZtJk_4rG88UGs5ngtL7d14suSsnlgZ5KPcKA/edit#) for more details.

## Proposed solution

Add a new endpoint `/eth/v2/validator/register_validator` to the beacon API spec. See [step 2 of design doc](https://docs.google.com/document/d/1J9Kv2LNZtJk_4rG88UGs5ngtL7d14suSsnlgZ5KPcKA/edit#heading=h.2quh84kolrvb). Also, see the first attempt to add the endpoint [here](https://github.com/ObolNetwork/beacon-APIs/pull/1).

### Out of Scope

None.

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/4) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
