### ISSUE TITLE
Generalise and document our proposers_config endpoint

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1643]
## Problem to be solved

We are adopting the Teku model of representing validators and their specific overrides (timestamp, pukey, gaslimit, etc) in JSON for the near term to coordinate MEV boost registrations. We need to put this enpoint on a nice subpath of validatorAPI that leaves space for other child pages that are customised for e.g. vouch. This api route and its structure should be documented in the docs and well explained in mev guides. We should analyse the validator clients and come up with an understanding of how many implementations this approach might work for, and how many would need to commit dev hours to support it. Understanding the effort involved in supporting mev registrations will be crucial for the bootstrap fund. 

## Proposed solution

If `teku_` is currently in the path of this proposer config endpoint, change it to something like `GET /eth/v1/validator/proposer_configuration`. Create a section in the docs describing this endpoint, its structure, its path, and how to specify it on supported clients (using a tab/accordion component ideally)

### Out of Scope

I would like for us to export a swagger file for the charon validatorAPI someday, will ticket eventually, out of scope for now, but would be useful for this non standard endpoint.

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kWT4FR7BVC/estimate/1) in Sizing - Protocol

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
