### ISSUE TITLE
Add linter to always require alias for an import

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1684]
## Problem to be solved

We want to ensure that "github.com/decred/dcrd/dcrec/secp256k1/v4" is always imported with the "k1" alias.

## Proposed solution

Add a lint which looks through imports across all go files and errors if the package isn't imported with the given alias. Generally, the behavior could be as follows:
```
alias-linter:
- ["k1", "github.com/decred/dcrd/dcrec/secp256k1/v4"]
- ["eth2api", "github.com/attestantio/go-eth2-client/api"]
...
```

### Out of Scope

None.

**Comment by corverroos** [comment]
can just configure normal regex linter with `^\t"github.com/decred/dcrd/dcrec/secp256k1/v4"`, no need for special import-alias linters.
