### ISSUE TITLE
Support aggregation duties in teku

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1725]
## Problem to be solved

Add support for aggregation duties in [teku](https://github.com/ConsenSys/teku).

## Proposed solution

This is part of the [epic](https://github.com/ObolNetwork/charon/issues/1715).

### Out of Scope

The plan is to complete this ticket by M1.

**Comment by thomasheremans** [comment]
Share integration doc with Ben @xenowits

**Comment by thomasheremans** [comment]
**Story Points: 8**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/12) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by xenowits** [comment]
The teku has started implementing this, see:
* https://github.com/Consensys/teku/pull/8019
* https://github.com/Consensys/teku/pull/8015
