### ISSUE TITLE
Maybe chunk BN requests

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1733]
## Problem to be solved

[go-eth2-client states](https://github.com/corverroos/go-eth2-client/blob/master/http/validators.go#L31-L37) that individual BN requests shouldn't be larger than 8k.

```
// A request should be no more than 8,000 bytes to work with all currently-supported clients.
```

Charon doesn't support chunking at all. This might be a problem.

## Proposed solution

- Identify whether this is actually a problem.
- If so, implement a "generic" json array splitter and chunch all slice based calls.

### Out of Scope

If there is anything to highlight as out of scope for this issue, please outline it here.

**Comment by gsora** [comment]
This may become an issue with larger clusters (i.e. lots of validators)
