### ISSUE TITLE
Add `Makefile` to simplify `go build`

### ISSUE THREAD

**Issue by gsora** [ObolNetwork/charon#1748]
Right now the Charon codebase has a few `go build` in code, Dockerfile and GitHub actions.

Since the addition of a cgo-based dependency (Herumi BLS implementation) we have to compile the resulting Go binary by statically linking Glibc, and to do so we need a quite long `go build` instruction.

To avoid disruption in CI and local tests, I propose we add a `Makefile` that embeds all the Go flags and `build` flags needed to create a cross-platform binary.

**Comment by corverroos** [comment]
we have removed all the `go build`s and replaced them with `docker build`

**Comment by corverroos** [comment]
I do not think this is required anymore, closing
