### ISSUE TITLE
Lighthouse with beaconmock sometimes fails hit `/eth/v1/validator/prepare_beacon_proposer`

### ISSUE THREAD

**Issue by gsora** [ObolNetwork/charon#1764]
# 🐞 Bug Report

Probably related to #1736, exhibits the same behavior: seemingly random connection resets and presumed early EOF.

## 🔬 Minimal Reproduction

<pre><code>
docker-compose logs -f vc0-lighthouse | grep "/eth/v1/validator/prepare_beacon_proposer"
</code></pre>

## 🔥 Error

<pre><code>
Error: Reqwest(reqwest::Error { kind: Request, url: Url { scheme: "http", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(3600), path: "/eth/v1/validator/prepare_beacon_proposer", query: None, fragment: None }, source: hyper::Error(IncompleteMessage) })
</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
Ubuntu Linux 22.10
  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
  <code>
v0.13.0
  </code>
</pre>

**Comment by thomasheremans** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/11) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
