### ISSUE TITLE
Optionally output exit messages at the end of a `charon dkg` and `charon create cluster` with the `--prepare-exit`

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1772]
# 🎯 Problem to be solved
We need an easier way to exit a validator. We also need to grant assurances to end users that they can trust that a DV they delegate to can exit. How about we sign legitimate exit messages at the end of the DKG phase when we also sign deposit data? Can we trust every operator with an exit message? I think we can risk it, as it basically means this entire cluster is now consensual because anyone could exit at any time if they wanted to. 

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Write `exit-data.json` for all validators in a cluster to `.charon`. Potentially happy to explore just making this the default for now while on testnet. 

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by corverroos** [comment]
@OisinKyne should we either:
 - create a single `exit-data.json` file containing an array of json objects, one for each validator? which would require the user to somehow select which validator to exit using pubkey or index or something.
 - or, create multiple `exit-data-0x123123123.json` files, one for each validator? So the user will need to select the file they provide to the tool that will process it?

**Comment by OisinKyne** [comment]
Don't feel extremely strongly either way, I think I would see what we can copy in terms of the eth2-staking-cli beginning to support exits design (I hear) and how ethdo does it. 

I imagine that we will probably make a UI page on the launchpad where you will upload your file and click an exit + confirm button. I would also imagine that in our 'one cluster per charon client' setup, and with balance skimming already being a thing, selectively exiting a subset of validators would be less common than broadly exiting that obol cluster in its entirety, and having 1000 exit files would be annoying most of the time, and convenient/safer infrequently. So I would probably favour something symetrical/stylistically like `deposit-data.json` personally.
