### ISSUE TITLE
Set a constant gauge for upstream `/eth/v1/node/version`

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1773]
# 🎯 Problem to be solved

We want to get more visibility into our upstream consensus client types, to try and spot a pattern when we are more multi client and something is affecting many operators across the network.

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

 I originally wanted to say, lets manually add a label to the prometheus.yml file when setting an auth token. And I figured that *might* work, but that also might be kind of messy. Instead lets just poll the upstream BN at like startup or network reconnection (nice and infrequent, no need to add more load at the epoch boundary). That outputs what it gets back as a prom metric. 

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by corverroos** [comment]
Suggest polling once every 10min, remember to clear the previous value (set gauge to 0).
