### ISSUE TITLE
Include deposit data in the lockfile

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1775]
# 🎯 Problem to be solved

A client wants to be a DV creator via the API. The create a definition file. The operators use the launchpad operator flow to sign and do the dkg. They publish the definition file. The creator can see the definition file, and the validators it would like to activate, however, it does not have the deposit data to send to the deposit contract. Those files are still sitting on operators devices where the creator can't access.

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Add an optional field to the validators object in the distributed_validators array called `deposit`, that includes a valid deposit message for the corresponding `withdrawal_address` alongside it. 

# 🧪 Tests

- Testcase: Lockfile validation should fail if `distributed_validators[*].deposit.withdrawal_credential  !== "0x010000000000"+ distributed_validators[*].withdrawal_address[2:]`

- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by corverroos** [comment]
Add the following field:
```
{
  definition: {...}
  distributed_validators: [
    {
      distributed_public_key: "0x123...",
      public_shares: [....]
      deposit: {
       {
          "pubkey": "80d0...",
          "withdrawal_credentials": "0100000...",
          "amount": 32000000000,
          "signature": "ab757712...",
          "deposit_message_root": "b4376b...",
          "deposit_data_root": "d402b324...",
          "fork_version": "00001020",
          "network_name": "goerli",
          "deposit_cli_version": "2.3.0"
        },
      }
    }, ...
  ]
}
```
