### ISSUE TITLE
Fix sync committee duties in simnet for large clusters

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1806]
# 🐞 Bug Report

### Description

Sync committee duties are failing in a simnet cluster with large number of validators (for ex: cluster with 100 validators).

### Has this worked before in a previous version?

I don't think so.

## 🔬 Minimal Reproduction

Run the following command with only sync committee duties enabled:
```
compose new --build-local --validator-types=mock --num-validators=100 --nodes=10 --insecure-keys=true --simnet-slot-duration=6s && compose auto
```

## 🔥 Error

Here's the list of errors observed:
<pre><code>
Peer exchanged invalid partial signature: invalid signature: beacon api domain: context deadline exceeded
Peer exchanged invalid partial signature: invalid signature: beacon api spec: context deadline exceeded
Peer exchanged invalid partial signature: invalid signature: getting slots per epoch: beacon api slots_per_epoch: context deadline exceeded
</code></pre>

Apart from this increase in p2p ping latencies and beacon API request latency was also observed:
![Screenshot 2023-02-14 at 9 28 53 PM](https://user-images.githubusercontent.com/37813203/218790739-7db8abfe-52b9-4bd1-930f-ada269ed4bae.png)
![Screenshot 2023-02-14 at 9 29 08 PM](https://user-images.githubusercontent.com/37813203/218790759-83895045-d701-4f60-a62e-017b0d62c5ed.png)

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>
macOS Ventura 13.1
  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
  <code>
v0.13.0/bc73565
  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/27) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
