### ISSUE TITLE
Write a charon threat model document 

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#1811]
# 🎯 Problem to be solved

We would like to explain to would be security researchers and attackers what we think the threat model for a distributed validator is, because that will help them both visualise the 'attack surface', as well as probe around for things we maybe haven't considered because they see little reference to it in this document. 

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Write a threat model document related to charon, paying attention to:

- [ ] Its identity private key and the safety of it
- [ ] Its supply chain and what we are doing to keep that safe (point at EV doc to show how we are trying to fortify)
- [ ] Its access to the ethereum validator private keys (during creation, if an operator doesn't explicitly take them away from us, if a validator can be exfiltrated, whether they are loaded unencrypted into the same memory as charon is running in, container escape risk. etc)
- [ ] Its risk to one another within a cluster
- [ ] Its risk to others outside a cluster interfering with it
- [ ] Its risk to a malicious BN
- [ ] Its risk to a malicious relay
- [ ] Its risk to a malicious validator giving things to sign with known pre-images or weird private keys designed to garner cryptographic information about their counterparties private keys. 

This write up should start in google docs and be published in markdown to our obol docs after acceptance (separate ticket on docs page to be made)

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by gsora** [comment]
Started working on the document here: https://docs.google.com/document/d/1ezMy1J5S1qc5qhElquWklOXrx70Cv-4SgztDH1CgU3s/edit#

**Comment by gsora** [comment]
>  Its risk to a malicious validator giving things to sign with known pre-images or weird private keys designed to garner cryptographic information about their counterparties private keys.

I would leave this one out, we're not in a position to audit BLS12-38.

**Comment by OisinKyne** [comment]
> > Its risk to a malicious validator giving things to sign with known pre-images or weird private keys designed to garner cryptographic information about their counterparties private keys.
> 
> I would leave this one out, we're not in a position to audit BLS12-381.

I favour we include it, I think it could be a legitimate threat to us if e.g. once every 4 slots a bad charon is proposing to us either fake consensus games signed by SECP256K1 with a known pre-image, or something similar at the BLS signature level, to gradually get its peers to snitch on themselves with respect to their private keys. Feels like over a few weeks or months you might be able to get something (but like people will be mad at you if you look offline to them for months)

**Comment by OisinKyne** [comment]
Just throw it in as a bullet point under `what could the trusted peers in a cluster do to harm us? / (Its risk to one another within a cluster)`

**Comment by gsora** [comment]
I addressed all the points in the document mentioned earlier in this conversation, please take a look and let me know what you think!

**Comment by gsora** [comment]
I have integrated all the suggestions in the document alongside a small conclusion. Please do let me know if you find anything else noteworthy, otherwise I'll go ahead and close this isssue.

**Comment by gsora** [comment]
Update: since this issue has been open for a long time I'll close it: the document is more or less in the state everyone wants and we can iterate further if we need it once we move to the official docs page/blog post.
