### ISSUE TITLE
Add prometheus counter for block proposals

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1812]
# 🎯 Problem to be solved

We want data to understand types of block proposals (normal vs blinded) across all charon clusters. We also want to understand how many validator registrations are successful.

# 🛠️ Proposed solution

Add a prometheus counter (`promauto.NewCounterVec`) to `validatorapi/metrics.go` which records HTTP status codes (2XX, 4XX and 5XX) for:
* publish blinded block proposals - [/eth/v1/beacon/blinded_blocks](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlindedBlock)
* publish block proposals - [/eth/v1/beacon/blocks](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/publishBlock)
* validator registrations - [/eth/v1/validator/register_validator](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Validator/registerValidator)

```go
	statusCodes = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "core",
		Subsystem: "validatorapi",
		Name:      "request_total",
		Help:      "The total number of requests per endpoint with status code",
	}, []string{"endpoint", "status_code"})
```

Sample queries can be like:
```
statusCodes{endpoint:"submit_blinded_block", status_code: 200}
statusCodes{endpoint:"submit_block", status_code: 400}
statusCodes{endpoint:"submit_validator_registration", status_code: 500}
```

Use these metrics to create panels in our central grafana dashboard (`charon-overview`) as well as aggregate view (`clusters-aggregate-view`).

# ❌ Out of Scope
None.

**Comment by OisinKyne** [comment]
For this, can this now be simplified to 'grafana panel' instead of prometheus counter?

**Comment by corverroos** [comment]
This is already instrumented:
```
	latencyHist = promauto.NewHistogramVec(prometheus.HistogramOpts{
		Namespace: "app",
		Subsystem: "eth2",
		Name:      "latency_seconds",
		Help:      "Latency in seconds for eth2 beacon node requests",
	}, []string{"endpoint"})

	errorCount = promauto.NewCounterVec(prometheus.CounterOpts{
		Namespace: "app",
		Subsystem: "eth2",
		Name:      "errors_total",
		Help:      "Total number of errors returned by eth2 beacon node requests",
	}, []string{"endpoint"})
```

- 4xx,5xx is: `app_eth2_errors_total{endpoint="foo"}`
- 2xx, is: `app_eth2_latency_seconds_count{endpoint="foo"}-app_eth2_errors_total{endpoint="foo"}`

**Comment by corverroos** [comment]
Closing this as grafana panels can simply be added for existing metrics.
