### ISSUE TITLE
Add `DepositAmount` field to cluster definition

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1818]
# 🎯 Problem to be solved

We have a use-case (rocketpool) where we want to change the `deposit_data.amount` to a different value (eg: 16) than the default 32 ETH.

# 🛠️ Proposed solution

The proposed solution is to add a new field `deposit_amount` to `cluster-definition.json` file. 

Add the following to `cluster/definition.go`:
```
// DepositAmount defines the amount of ether to specify in the deposit data file.
DepositAmount int `json:"deposit_amount" ssz:"uint64" config_hash:"8" definition_hash:"8"`
```

* Note that this brings the [dv-launchpad](https://github.com/ObolNetwork/dv-launchpad) into scope since the cluster definition is created by the launchpad.
* The fact that the operators already decide on the amount to be deposited prior to the DKG makes the solution less tricky and intuitive.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on launchpad UI

**Comment by corverroos** [comment]
Shouldn't this be per validator?

**Comment by thomasheremans** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/kTqTIeSZ2w/estimate/33) in Ongoing Sizing

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
