### ISSUE TITLE
Implement alpha add validator local command

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1887]
# 🎯 Problem to be solved
Once the new cluster state datastructure has been implemented, #1846, including the `add_validator` operation. We need to add support for generating additional keys and generating the cluster state file to a cli command. We can start with a similar command to `charon create cluster` as this is easiest to implement.

# 🛠️ Proposed solution

See design [doc](https://docs.google.com/document/d/1fpC4BCPeqOL_zKlDWYetuSL87ucVWE4COroIIo1c-lY/edit#).

Create a new command: `charon alpha add-validators-local`

- It takes a legacy lock file as input
- It takes withdrawal addresses and fee_recipients as input
- It generates keys
- It generates a new cluster state file with the `legacy_lock` and `add_validators` mutations

**Comment by xenowits** [comment]
Let's solve this in the following phases:
1. Add `charon alpha add-validators-solo` command to `cmd` package. It does not contain the actual run logic.
2. Add `add validators` logic to the subcommand. This involves using the `state` package. Ex: `state.NewGenValidators`, `state.NewNodeApprovalsComposite` etc.
  * This may involve some number of PRs.
3. Save the new cluster state file to disk
