### ISSUE TITLE
Deneb design doc

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#1900]
# 🎯 Problem to be solved

The next ethereum consensus layer fork after capella is named [deneb](https://github.com/ethereum/consensus-specs/tree/dev/specs/deneb). This upgrade adds proto-danksharding, ie, [EIP-4844](https://www.eip4844.com/) to the beacon chain. 

We want charon to be ready for deneb.

# 🛠️ Proposed solution

Write a design document to understand what changes are needed in charon to support the deneb hardfork.

# 🧪 Tests

We should test charon to ensure it works properly before the deneb fork comes around, which is tentatively on 12th April, 2023.

- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by corverroos** [comment]
@gsora the first step would to look at the new endpoints and verify that we will be able to add them either without changes or whether the proposed endpoints are not compatible with middleware DVT and would require additional changes.

**Comment by gsora** [comment]
I see no explicit new endpoints added in Deneb by the looks of the linked PR, as of today.

There are new/modified objects though: the `BlockContent` definition changed to accomodate sidecars.

**Comment by gsora** [comment]
Looking at the PRs on the beacon API repo, there's this: https://github.com/ethereum/beacon-APIs/pull/286

**Comment by dB2510** [comment]
Just mentioning here for the record, we should participate in devnet 5 of deneb upgrade this week to understand how it will us affect directly.  If there are some changes in deneb spec that we need to propose in order to support deneb with charon then we should communicate those asap with core devs since it is still in development phase.
For more details: https://www.galaxy.com/research/insights/ethereum-all-core-developers-consensus-call-107/
https://hackmd.io/@inphi/HJZo4vQGn

cc: @gsora

**Comment by boulder225** [comment]
running charon in the deneb testnets and getting charon passing the deneb hive tests

**Comment by gsora** [comment]
We need to extend compose to execute a full Eth2 local network, with our custom genesis etc.

**Comment by dB2510** [comment]
Here's the requirements doc for deneb upgrade: https://docs.google.com/document/d/1WcJ4P-_JO937biy4nzwrYyWrYapldiTlAyOQU0qoCo0/edit

**Comment by xenowits** [comment]
The protocol team has agreed on implementing the solution 2 as mentioned in the doc as it is simple and easy to implement.
