### ISSUE TITLE
Log peer info at the start of DKG

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1912]
# 🎯 Problem to be solved
We have got a request from lido that it is really hard to map peer names to their ethereum addresses at scale when they are conducting DKG ceremonies in large groups. Current solution is they need to ask every operator about their peer name and map their ethereum address. We can log this info as "Peer Summary" during DKG ceremony.

# 🛠️ Proposed solution

Log a peer summary at the start of DKG ceremony which includes the following (one info log per peer):
  - Peer p2p name
  - operator (eth) address
  - Index=int
  - you=star

```
09:50:37.917 INFO            Peer summary                             {"peer": "lazy-yesterday", "address": "0x12345678901234567890", "index": 0}
09:50:37.917 INFO            Peer summary                             {"peer": "fierce-room", "address": "0x12345678901234567890", "index": 1, "you": "⭐️"}
```

**Comment by corverroos** [comment]
I would rather implement this feature: https://github.com/ObolNetwork/charon/issues/1655

**Comment by corverroos** [comment]
Note a proper long term solution is to add nicknames to the lock file.
