### ISSUE TITLE
Enhance `dkg.checkWrites()` logic

### ISSUE THREAD

**Issue by gsora** [ObolNetwork/charon#1919]
# 🐞 Bug Report

### Description

`dkg.checkWrites()` should be enhanced to prevent situations like the one described in [point 4 of this document](https://docs.google.com/document/d/1Pfcv3NUTlJpMF_tmOQbSwWHYN0Qv1GzgIsKG8XLkWUM/edit#).

### Previous work

https://github.com/ObolNetwork/charon/pull/1915 tries to handle some of the edge cases at the end of the DKG process, although those should be embedded in `dkg.checkWrites()` since it runs before the process takes place.

**Comment by gsora** [comment]
I would propose the following simple solution: if the data directory has *anything* except a file named `charon-enr-private-key`, error out and tell the user to clean up their data directory without deleting the private key.

Thoughts? @corverroos @OisinKyne

**Comment by corverroos** [comment]
Yeah, sounds good. Please do not remove checks that check that files and directories can be created.

**Comment by gsora** [comment]
Implemented.
