### ISSUE TITLE
Validate duty data

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1922]
# 🐞 Bug Report

### Description

We must verify all duty data received over the wire:
 - duty definition from eth2client
 - unsigned data from eth2client and consensus
 - signed data from parsigex 

We should at least check the following:
 - ensure slot matches duty slot
 - ensure pubkeys match data set pubkey.
 
 Proposed solution:
  - Add `core.VerifyDutyDefinitionSet(Duty, DutyDefinitionSet)`
  - Add `core.VerifySignedDataSet(Duty, SignedDataSet)`
  - Add `core.VerifyParSignedDataSet(duty, ParSignedDataSet)`
  - call these as soon as the objects are received over the wire.

**Comment by gsora** [comment]
Is https://github.com/ObolNetwork/charon/pull/2079 sufficient to close this?
