### ISSUE TITLE
DKG reconnect deadlock bug

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#1925]
# 🐞 Bug Report

### Description

There is a bug in DKG sync protocol that results in some peers deadlocking during shutdown. This is triggered when relay connections are recycled at an exact moment during the shutdown process which results in a deadlock and the DKG hanging and not completing for some peers.

### Has this worked before in a previous version?

No. It has been present in original sync protocol introduced in v0.13.

## 🔬 Minimal Reproduction

See screenshots below.

**Comment by corverroos** [comment]
![image](https://user-images.githubusercontent.com/37813203/227197525-cf9c0d94-4a19-4708-bab7-7e2d506b3cbc.png)
![image](https://user-images.githubusercontent.com/37813203/227197932-94fd2344-37fc-4d61-916e-d66a4df5bd0d.png)
![image](https://user-images.githubusercontent.com/37813203/227197955-cee808ef-0675-4557-8632-686a7e2efa8b.png)
