### ISSUE TITLE
Default on CLI commands to mainnet

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon#1969]
Default for charon for every CLI command needs to be mainnet, risk of invalid depositing on mainnet is >> more severe than messing up a goerli one. Every doc and guide needs to be updated to include --network goerli as a result.

**Comment by corverroos** [comment]
This task is blocked until the launchpad explicitly specifies the `--network=<goerli/mainnet>` otherwise this will break goerli lanchpad triggered DKGs.

**Comment by corverroos** [comment]
Assigned to @HananINouman while this is blocked on launchpad side
