### ISSUE TITLE
Nightly test doing long-running DKG

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon#1971]
# Problem to be solved

We need an integration type tests for long-wait DKG.

# Proposed Solution

Write a script/test that does a long-wait DKG using latest main and public relays. 

Suggest something like:
 - Start a new node every 10min node
 - Each node randomly stops for 2min in every 10min window.
 - DKG should complete within 10min after last node started. 
 
 Run this test once a day (at noon UTC)

**Comment by xenowits** [comment]
Next step is to add a github workflow to ensure this test runs once a day at noon UTC. 

We can use `on.schedule.cron` to schedule a cron task for this. See [codeql-analysis workflow](https://github.com/ObolNetwork/charon/blob/main/.github/workflows/codeql-analysis.yml#L20) for an example.
