### ISSUE TITLE
Fix Sigmap Prime Audit Results

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#1991]
# 🐞 Bug Report

### Description

Sigma Prime has completed the charon audit, see [report](https://drive.google.com/file/d/1wcKb89YxhYOZM6iTC_4cjr5JpOHdqUOm/view?usp=sharing) and [tracking sheet](https://docs.google.com/spreadsheets/d/1ot19VpKCblZx6RuzbkUMje963JdiAlvLDNrf-xBxahk/edit?usp=sharing).

Larger issues probably need their own github issues, but smaller issues can be directly linked to this issue.

- [x] #1997

**Comment by gsora** [comment]
After reviewing all the `panic()` usage in our codebase, we're going to mark OBOL-08 as WONTFIX.
