### ISSUE TITLE
Regularly attempt direct dials even if relay conns exist 

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2114]
# 🎯 Problem to be solved
We increased the relay connection limit to 1 hour. This reduces issues around connection recycling, but it had the unintended side-affect of increasing the duration before connections are upgraded to direct connections. 

This is due to libp2p not attempting to dial (create new connections) if existing connection is found. Since we now have long lived relay connections, they are used for the whole hour. Only after 1 hour, do we attempt another direct dial, which can succeed or fail, if fail, we wait another 1 hour.

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Libp2p has a feature called `network.WithForceDirectDial` that forced direct dialing even if proxied connections are present.

We can create a loop, that periodically (every 1min) calls `tcpNode.Connect(network.WithForceDirectDial(ctx), peer)` if no direct connections are present.

**Comment by dB2510** [comment]
@corverroos how about including `network.WithForceDirectDial(ctx)` in p2p/ping.go:
https://github.com/ObolNetwork/charon/blob/96af658642c017d4275cd701a528fd92c4f919e6/p2p/ping.go#L89

As `svc.Ping(network.WithForceDirectDial(ctx), p)`.

This would be more frequent than we want I think.
