### ISSUE TITLE
Sedge design doc

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2118]
# 🎯 Problem to be solved
We want to add support for charon to Sedge, but first need to analyse how this would work, what features are supported, what would need to be added, etc. 

# 🛠️ Proposed solution
Write a design doc that outlines the complexity and steps and process of adding charon to sedge. Also start chatting with Nethermind that we want to do this.

**Comment by xenowits** [comment]
Closing this in favour of https://github.com/ObolNetwork/charon/issues/2882
