### ISSUE TITLE
Error: mkdir: mkdir .charon: permission denied

### ISSUE THREAD

**Issue by awesomer777** [ObolNetwork/charon#2131]
# 🐞 Bug Report

### Description

 A clear and concise description of the problem...

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Error
I met this error when running following cmd:
```
docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.15.0 create cluster --name="mycluster" --withdrawal-addresses="${WITHDRAWAL_ADDR}" --fee-recipient-addresses="${FEE_RECIPIENT_ADDR}" --nodes 6 --threshold 5
```
<pre>
Error: mkdir: mkdir .charon: permission denied
<code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
Ubuntu
  <code>

  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
latest
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by corverroos** [comment]
Hi @awesomer777 , the problem is probably related to your docker installation. Have you checked out our FAQ? Specifically, https://docs.obol.tech/docs/int/faq/errors#docker-permission-denied-error.

Feel free to open the ticket if this doesn't resolve it.
