### ISSUE TITLE
Pre-generate validator registrations

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2172]
# 🎯 Problem to be solved
The current builder-api validator registration endpoint isn't compatible with DV middleware, see https://github.com/ObolNetwork/charon/issues/1643 and this [design doc](https://docs.google.com/document/d/1J9Kv2LNZtJk_4rG88UGs5ngtL7d14suSsnlgZ5KPcKA/edit#heading=h.abi7h3595rh9). 
 Changing the spec and getting all VC implementations to implement it is the proper long term solution. 

This is short term workaround is to pre-generate validator registration messages during the DKG, to store them in the lock file, and to broadcast them once an epoch when `--builder-api=true`.

# 🛠️ Proposed solution
- [x] Approved design doc: [link](https://docs.google.com/document/d/1lCYiEv7JmVYymp4CBrEvExj3WNmSqWVvZwl9dwATCmA/edit#)
- [x] Core team consensus on the proposed solution

See design doc.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by boulder225** [comment]
https://grafana.monitoring.gcp.obol.tech/d/TcqKfPx4z/engineering-okrs?orgId=1&from=now-90d&to=now

**Comment by boulder225** [comment]
update docs pls @gsora @dB2510
