### ISSUE TITLE
Support DutyRandao in validatorapi

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#218]
## Problem to solve

We are adding support for DutyRandao, but the validatorapi service doesn't support it yet.

## Proposed solution

- When the VC requests a new unsigned block, it provides the randao reveal in the request
- See https://ethereum.github.io/beacon-APIs/#/ValidatorRequiredApi/produceBlockV2
- Add support for above endpoint to validatorapi/router.go and validatorapi.go
- For now, just extract the randao reveal, verify the signature, store it parsigdb and return an error.
- Define `(De|En)codeRandaoParSignedData`, using eth2p0.BLSSignature as the type.
- Get the `sigRoot` for verification by inferring epoch from the provided slot
- Store the randao reveal in the parsigdb.

**Comment by leolara** [comment]
@dB2510 finished the wiring of this
