### ISSUE TITLE
Support an optional `callback_urls` array in a cluster definition

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#2188]
# 🎯 Problem to be solved

See [here](https://github.com/ObolNetwork/obol-api/issues/222) for the detailed proposal. 

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Describe the solution to be implemented

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

# 👐 Additional acceptance criteria

All of our test cases have a config v1.7 type like this (and older ones for regression reasons)

# ❌ Out of Scope

- [ ] Validating the URLs beyond general string/json validation
- [ ] No calling these URLs needed, that's an API task

**Comment by corverroos** [comment]
Putting this on ice until the open questions are adresses, see [discord](https://discord.com/channels/930779837218562078/1107942778912124979).

**Comment by corverroos** [comment]
We have decided that creator will just poll the obol-api, so callbacks or webhooks are not supported.
