### ISSUE TITLE
Add node_signatures to lock file

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2204]
# 🎯 Problem to be solved

A valid cluster lock can be generated by anyone from a valid cluster definition. This is because the operators or nodes do not sign the resulting generated validators, the `signature_aggregate` is only signed by the validators themselves. This has been addressed in the new cluster state, but should be addressed in the legacy lock as well.

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Steps:
- Add a `node_signatures` field to the cluster lock that contains all charon_enr_private_key k1 signatures of the lock hash. 
- Ensure that lock verification checks this 
- Generate and exchange these signatures during the DKG

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by boulder225** [comment]
@OisinKyne asks "can we call it `enr_signatures` or `operator_enr_signature` or something maybe? `node` is a new concept not mentioned in the rest of our code to my knowledge" @gsora FYI
