### ISSUE TITLE
Nightly tests are failing

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2239]
# 🐞 Bug Report

### Description

The nightly tests are failing every time.

### Has this worked before in a previous version?

I think so, not sure actually.

## 🔬 Minimal Reproduction

https://github.com/ObolNetwork/charon/actions/runs/5079707417

**Comment by gsora** [comment]
After merging #2253, nightly tests are now passing: https://github.com/ObolNetwork/charon/actions/runs/5121234674

Closing this issue as completed.
