### ISSUE TITLE
Change current config version to v1.6

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2246]
# 🎯 Problem to be solved

Config `v1.7` is not going to be released with the upcoming release `v0.16`. However, `v1.7` is the current config version.

# 🛠️ Proposed solution

* Make `v1.7` as the draft version instead of the `currentVersion`. 
* Make `v1.6` as the `currentVersion` instead.
* See https://github.com/ObolNetwork/charon/blob/main/cluster/version.go

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by dB2510** [comment]
closed by #2247
