### ISSUE TITLE
Error when combining keys of Cluster with version 1.4

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon#2300]
# 🐞 Bug Report

### Description

I tried to combine the keys of charon-perf-1. The cluster-lock version is 1.4.
I used the Charon image tag 0.14 to combine but received an error - 
`docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.14.0 combine --cluster-dir=cluster
 INFO            Recombining key shares                   {"input_dir": "cluster"}
Error: cannot open lock file: cluster lock hash verification failed: invalid definition: invalid config hash`

Next, i updated the version to 1.5, but that did not work either as these two versions were incompatible.
Then we had to manually disable hash and signature checks in `Charon` code and compile a binary to make the combine work successfully.

## 🔬 Minimal Reproduction
Download the cluster details from `gs://charon-clusters-config/charon-perf-1`
Copy into a .charon/cluster folder
Copy the cluster-lock.json into each of the `node` folders
Run the command `docker run --rm -v "$(pwd):/opt/charon" obolnetwork/charon:v0.14.0 combine --cluster-dir=cluster`

## 🔥 Error

<pre><code>
 INFO            Recombining key shares                   {"input_dir": "cluster"}
Error: cannot open lock file: cluster lock hash verification failed: invalid definition: invalid config hash`
</code></pre>

**Comment by gsora** [comment]
The process and the tooling are without fault here, but the lock file used was not: since it was modified for the purpose of running the cluster without having to rekey everything.

**Comment by LukeHackett12** [comment]
@sugh01 I would suggest changing the fee recipient to a dafault `0x000...` address and retrying the combination. I think that is what was modified.
