### ISSUE TITLE
Fix unmarshal issues with `go-eth2-client` version v0.17.0  

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#2333]
# 🐞 Bug Report

### Description

`go-eth2-client` has recently introduced some changes on some types we use. Refer: https://github.com/attestantio/go-eth2-client/commit/f27aaab667155c5cc638321228a6b6b85de4a4c0#diff-5925e41dbeb726f19b2462689701ef3fa153073c95f8db415f049c3c89379fe7. 
These changes breaks unmarshal `SignedEpoch` in parsigex.

### Has this worked before in a previous version?

Yes, the previous version in which this bug was not present was `go-eth2-client` version prior v0.17.0. And charon version v0.16.0.

## 🔬 Minimal Reproduction

Run with charon tag: `b8f1cc7`

## 🔥 Error

This error has been found in node `fine-jewellery` in core team cluster.

![Screenshot 2023-06-19 at 1 32 57 PM](https://github.com/ObolNetwork/charon/assets/37813203/cdc3b73e-7bab-4f5f-b4a8-2b1fe6de8676)

<pre><code>
LibP2P handle stream error: convert parsigex proto: unmarshal signed randao: unmarshal json: unmarshal signed epoch: invalid prefix {"duration": "174.329µs", "peer": "energetic-child", "protocol": "/charon/parsigex/1.0.0"}
</code></pre>

## 🌍  Your Environment

**What version of Charon are you running? (Which release)**

<pre>
  <code>
b8f1cc7
  </code>
</pre>

**Comment by boulder225** [comment]
@dB2510 
> The issue is with SignedEpoch unmarshal in `eth2util/types`. This struct contains `ethp0.BLSSignature` which has got a new `UnmarshalJSON` method in latest` go-eth2-client` version v0.17.0. In that method it does some checks like signature should be prefixed with 0x and it should be a string. We just need to take care of this in `MarshalJSON` in `eth2util/types`.

**Comment by dB2510** [comment]
Note on this issue regarding compatibility with previous version:
This might be tricky to retain backwards compatibility. v0.17.0 should be backwards compatible with v0.16.0. So the solution isn't just to ensure v0.17 can unmarshal data sent by another v0.17, v0.16 (which we cannot change anymore) should also be able to unmarshal data from a v0.17.0. 

We need to take care of backwards compatibility of v0.17.0 with v0.16.0 as well as forwards compatibility of v0.16.0 with v0.17.0.

**Comment by corverroos** [comment]
This starts the following migration:

v0.16 marshals legacy and unmarshals legacy only.
v0.17 marshals legacy, but supports unmarshalling both new and legacy.
v0.18 will marshal new, but will support unmarshalling both new and legacy
v0.19 will marshal new and will unmarshals new only
