### ISSUE TITLE
cluster hashes should match in manifest and lock

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2335]
# 🎯 Problem to be solved

Users can provide both `cluster-manifest.pb` and `cluster-lock.json` files to charon commands such as `charon run`. In such cases, for safety, we can verify that the cluster hashes in both these files match. 

# 🛠️ Proposed solution

If both legacy lock and manifest files are found, load both files. Ensure that the cluster hashes match, ie, that the manifest contains that legacy lock. Else error with mismatching manifest and legacy lock found.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

# 👐 Additional acceptance criteria

None

# ❌ Out of Scope

None

**Comment by OisinKyne** [comment]
I don't think we should have definition and lock files as part of the manifest flow, what is the benefit? what does the user journey look like? How does the launchpad flow change to accomodate this?

**Comment by corverroos** [comment]
@OisinKyne see our comments in #2334. Adding support for both legacy lock files and new manifest files is required to support both old and new cluster configuration with the same code base.
