### ISSUE TITLE
Create backup manifests

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2345]
# 🎯 Problem to be solved

When we run `charon alpha add-validators-solo` command, it changes (mutates) the loaded cluster and writes the mutated cluster to a `cluster-manifest.pb` file. This means the `cluster-manifest.pb` is overriden each time a new mutation is performed.

This maybe problematic if we want to revert to an older state in case there's a bug in our code.

# 🛠️ Proposed solution

The solution is to create backups of manifest files before overriding.

* Write a backup file before modifying `cluster-manifest.pb`.
* Each backup file should be named with a lexicographic datetime (fancy way of saying reverse order so it sorts well). Timestamps in unix time aren't user friendly despite being sortable. cluster-manifest.pb.20230721183000"

* Note that backup file should only be created when the cluster is loaded from a cluster manifest file, not a legacy lock file.

^ We shouldn't be dragging tech debt along here, think we need to spec more carefully. 

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by OisinKyne** [comment]
Don't think this needs to be in a different folder. don't think it needs a flag. 

I think we just need to make a copy, can be like `cluster-manifest.pb.20230721183000`, and we just spit a new one of these out every time the `charon alpha add-validators` command runs, and if the program hits a panic, it has the ability to unwind the situation and leave a working `charon-manifest.pb` no matter what.
