### ISSUE TITLE
Cluster failing attestations with mixed node versions

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2357]
### Description:
The Canary clusters are experiencing issues with attestations with  mixed versions of v0.16.0 and v0.17-dev. To resolve the issue, I updated all nodes to run on the latest tag, which has resolved the problem. 

### Steps to reproduce:
1. Set up a 4 cluster with two nodes running on v0.16.0 and two nodes running on the latest tag.
2. Attempt to run attestations on the cluster.
3. Observe that attestations are failing.

### Expected result:
Attestations should be successful.

### Actual result:
Attestations are failing.

### Environment:
- Two nodes running on v0.16.0
- Two nodes running on the latest tag

**Comment by dB2510** [comment]
Closing this in favour of #2386
