### ISSUE TITLE
Relay throws error during a high volume dkg test (100 nodes)

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon#2376]
# 🐞 Bug Report

### Description

I performed a 100 node DKG test - 
Tested with relays -
`https://2.relay.obol.tech`
`https://1.relay.obol.tech`

DKG does not complete.

Relay throws error - 

`{caller: relay/relay.go:343, level: debug, logger: relay, msg: error reading stop response: stream reset, pretty: [35mDEBG[0m [32mrelay [0m error reading stop response: stream reset , ts: 2023-06-29T13:30:09.177666924Z}`

`{caller: relay/relay.go:474, level: debug, logger: relay, msg: error writing relay response: stream reset, pretty: [35mDEBG[0m [32mrelay [0m error writing relay response: stream reset , ts: 2023-06-29T13:30:09.172673635Z}`

`{caller: relay/relay.go:470, level: debug, logger: relay, msg: relay error: CONNECTION_FAILED (203), pretty: [35mDEBG[0m [32mrelay [0m relay error: CONNECTION_FAILED (203) , ts: 2023-06-29T13:30:09.177624624Z}`

`{caller: relay/relay.go:470, level: debug, logger: relay, msg: relay error: MALFORMED_MESSAGE (400), pretty: [35mDEBG[0m [32mrelay [0m relay error: MALFORMED_MESSAGE (400) , ts: 2023-06-29T13:30:09.177783175Z}`

<img width="1244" alt="image" src="https://github.com/ObolNetwork/charon/assets/19183308/a1da6345-966a-4b5b-a2c8-180e3f37bbd9">

## 🔬 Minimal Reproduction

```shell
compose new --external-relay https://2.relay.obol.tech --nodes=100 --keygen=dkg
compose define
compose lock
```

**Comment by corverroos** [comment]
100 node DKG isn't realistic, we only support max 31 node clusters.

**Comment by corverroos** [comment]
Closing as this is expected
