### ISSUE TITLE
Update selections endpoint description

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2396]
# 🎯 Problem to be solved

The client teams implementing aggregations have discussed the possibility of querying selections endpoints at the "start of an epoch" rather than at the "start of a slot".

Charon already supports this and "query at start of an epoch" would enable easy implementation in consensus clients. However, we should mention this explicitly in the beacon API spec since it is unclear currently.

# 🛠️ Proposed solution

* Raise a [PR](https://github.com/ObolNetwork/beacon-APIs/pull/6) to update the [beacon-API](https://github.com/ethereum/beacon-APIs) specs repo
* Update the [implementations guide](https://docs.google.com/document/d/1q9jOTPcYQa-3L8luRvQJ-M0eegtba4Nmon3dpO79TMk/edit#heading=h.mssb0822zapb) to explicitly state that client teams must query at epoch start
* Share the link to this PR with the client teams

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by dB2510** [comment]
Completed and PR has been raised: https://github.com/ethereum/beacon-APIs/pull/368
