### ISSUE TITLE
 Add holesky fork version to charon

### ISSUE THREAD

**Issue by LukeHackett12** [ObolNetwork/charon#2399]
# 🎯 Problem to be solved

Charon will need to be able to support [Holesky](https://github.com/eth-clients/holesky) testnet when it is released.

# 🛠️ Proposed solution

Once the Holesky fork version and genesis timestamp are known, add a new network var [here](https://github.com/ObolNetwork/charon/blob/20efac960c6fd135a184b31db36676544b27ee6f/eth2util/network.go#L28) and add it to supported networks. 
```go
	Holesky = Network{
		ChainID: 17000,
		Name: "holesky",
		GenesisForkVersionHex: "0x00017000",
		GenesisTimestamp: 1694786400,
	}
```

Also enable `--network=holesky` as an option for `create dkg` & `create cluster` commands.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by LukeHackett12** [comment]
added params based on the eth-clients repo, backed up by https://github.com/sigp/lighthouse/blob/stable/common/eth2_network_config/built_in_network_configs/holesky/config.yaml

**Comment by OisinKyne** [comment]
Looks like the params have been added, including the extradata being removed https://github.com/eth-clients/holesky
