### ISSUE TITLE
Implement Launchpad URL Return for `--publish` Command

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2423]
## 🎯 Problem to be solved
The `--publish` command, used at the end of the Distributed Key Generation (DKG) ceremony, currently does not provide a user-friendly way to access the new cluster dashboard. Users have to manually locate and navigate to the dashboard, which may be inconvenient and challenging for those unfamiliar with the system.

## 🛠️ Proposed solution
To improve user experience, the `--publish` command should be enhanced to return a launchpad URL directly pointing to the new cluster dashboard. This means that upon completing the DKG ceremony, users will receive an immediate link to their cluster dashboard, simplifying the process and improving usability. This solution will require modifications to the `--publish` command's functionality, specifically in the section dealing with the DKG ceremony's conclusion. The implementation should ensure the generated URL is accurate and functional, leading the user to the correct cluster dashboard.

**Comment by corverroos** [comment]
Cool, but given a `--publish-address` (default value is `https://api.obol.tech`) what should the url be we print in the terminal?

**Comment by boulder225** [comment]
@Battenfield

**Comment by boulder225** [comment]
`{base_url_endpoint}/clusters/details/?lockHash={lock_hash}` @f1lander
