### ISSUE TITLE
align hash timestamp to eth2

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2436]
# 🐞 Bug Report

### Description
The timestamp format of the validator registration in hash calculation needs to be aligned with eth2. This alignment is necessary to avoid confusion between the timestamp in `cluster-lock.json` and the format used to calculate the lock hash.

**Comment by corverroos** [comment]
I do not agree with RFC3339, rather align with eth2 spec.

**Comment by dB2510** [comment]
closed by #2430
