### ISSUE TITLE
Health check for too many metrics

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2446]
# 🎯 Problem to be solved
We have had a problem of prometheus metrics using to many labels (high cardinality) which results in memory leak in charon and overloading of the prometheus infra.

We need to monitor and alert when metric labels grows too much. 

# 🛠️ Proposed solution
Two step solution:
- Add a warning health-check that alerts if there are more than `X*validators` metrics in a metrics family. Suggest using X=100 as a start. 
- Add a central monitoring pager duty alert (similar to high memory usage alet) for this check

**Comment by pinebit** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2446?planning-poker) with Zenhub @gsora

**Comment by pinebit** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2446?planning-poker) with Zenhub @KaloyanTanev
