### ISSUE TITLE
Support building proper release from source locally

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2453]
# 🎯 Problem to be solved
We currently only support building official release docker images using the `build-push-deploy.yml` github action workflow. This sets the proper release version using go build flags. 

Users that want to build from source locally using `go build` end up with binaries with `v0.X-rc` versions which is confusing. 

We need a way for users to build any official easily from source locally with the proper release versions set.

# 🛠️ Proposed solution
Either write a makefile script that builds the charon binary setting the git tag as the version, effectily doing something like:
```
export GO_BUILD_FLAGS='-ldflags=-X github.com/obolnetwork/charon/app/version.version=${{ github.ref_name }}'
docker build --build-arg="GO_BUILD_FLAGS=$GO_BUILD_FLAGS"
```

Another option would be to write a script/command/tool that calls the github action locally, maybe using https://github.com/nektos/act.

Write documention to allow users to build any official release.

**Comment by corverroos** [comment]
We need to confirm what the output artefact should be, is it a binary or a docker container?

**Comment by corverroos** [comment]
suggest we use go-releaser, see https://github.com/ObolNetwork/charon/issues/2540

**Comment by Chainode** [comment]
It would be great if the solution would work with both a binary or a docker container as output.

**Comment by gsora** [comment]
We can mark this as done, Makefile has been merged in https://github.com/ObolNetwork/charon/pull/2896
