### ISSUE TITLE
Investigate whether our DKG is built on GG20

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2457]
## 🎯 Problem to be solved

The main problem to be addressed is the potential vulnerability in our Distributed Key Generation (DKG) protocol. The TSSHOCK attack, which allows a single malicious party to completely break the security of Threshold Signature Schemes (TSS) and perform a full private key extraction, could potentially affect our system. This attack, which leaves no trace and appears innocent to other parties, could result in significant cryptocurrency losses for both individual users and institutions. There is also an indication of two more vulnerabilities that need to be investigated apart from the one described.

## 🛠️ Proposed solution

The proposed solution includes several steps:

1. Investigate whether our DKG protocol is built on the GG20 scheme, which could potentially affect our susceptibility to the TSSHOCK attack.

2. If our DKG is built on GG20, we must review and potentially revise our protocol to mitigate this vulnerability.

3. In parallel, we should identify and investigate the two additional vulnerabilities that have been suggested.

4. Once these vulnerabilities have been thoroughly examined, we should develop and implement patches or other solutions to address them.

5. Finally, we should conduct rigorous testing and validation to ensure these solutions are practical and not introduce new vulnerabilities to our system.

### Sources
- https://www.blackhat.com/us-23/briefings/schedule/#tsshock-breaking-mpc-wallets-and-digital-custodians-for-billion-profit-33343
- https://twitter.com/fegge/status/1682322473553915904?
- https://drive.google.com/file/d/1zEgQcb4NDjFi8rvTb2cPD5b5Zxif1-5N/view

**Comment by corverroos** [comment]
GG20 is a 1-round ECDSA MPC algorithm, we do not do any ECDSA DKGs nor do we use GG20.
