### ISSUE TITLE
add `/eth/v2/beacon/blinded_blocks` to validatorapi

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2477]
# 🎯 Problem to be solved

A new `v2` endpoint to submit blinded beacon blocks to a beacon node has been recently added to the [beacon API specs](https://ethereum.github.io/beacon-APIs/#/). We need to support newer versions of validator clients quering this v2 endpoint.

# 🛠️ Proposed solution

Add support for the new [/eth/v2/beacon/blinded_blocks](https://ethereum.github.io/beacon-APIs/#/Beacon/publishBlindedBlockV2) endpoint to the `validatorapi` component.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by corverroos** [comment]
@xenowits do we know of any VCs that use this endpoint?

**Comment by xenowits** [comment]
@corverroos No, none of the VCs seem to use this `v2` endpoint. The following VCs are all using `v1` endpoint to submit blinded beacon blocks atm:
Teku: https://github.com/Consensys/teku/blob/22.12.0/data/beaconrestapi/src/main/java/tech/pegasys/teku/beaconrestapi/handlers/v1/beacon/PostBlindedBlock.java#L42
Lighthouse: https://github.com/sigp/lighthouse/blob/stable/validator_client/src/block_service.rs#L572 
Lodestar: https://github.com/ChainSafe/lodestar/blob/unstable/packages/validator/src/services/block.ts#L187
Nimbus: https://github.com/status-im/nimbus-eth2/blob/stable/beacon_chain/validator_client/block_service.nim#L252

**Comment by dB2510** [comment]
Closing this as it is completed as part of #2650
