### ISSUE TITLE
Improve track failure reason names

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2488]
# 🎯 Problem to be solved
The tracker failure reasons that we instrument and describe [here](https://github.com/ObolNetwork/charon/blob/main/docs/reasons.md#duty-failure-reasons) use names linked to the components or steps where the duty failed. This results in unintuitive logs and metrics which is hard for users to understand and require lookup in the reference.

We could improve operator UX by renaming these reasons to be more descriptive of the cause where applicable.

# 🛠️ Proposed solution

Few things we can do:
- Prefix "bug" to reasons that are unexpected, also put this in a separate section in the docs.
- If there is only one cause, use that as the reason, not the step.

Some suggestions:
- `bcast` -> `broadcast_bn_error`
- `chain_inclusion` -> `not_included_onchain`
- `consensus` -> `no_consensus`
- `fetcher_aggregator_failed_prepare` -> `failed_aggregator_selection`
- `fetcher_aggregator_few_prepares` -> `insufficient_aggregator_selections`
- `fetcher_aggregator_no_external_prepares` -> `no_aggregator_selections`
- `fetcher_aggregator_no_att_data` -> `missing_aggregator_attestation`
- `fetcher_bn` -> `fetch_bn_error`
- `fetcher_proposer_failed_randao` -> `failed_proposer_randao`
- `par_sig_ex_receive` -> `no_peer_signatures`
- `par_sig_db_insufficient ` -> `insufficient_peer_signatures`
- `validator_api ` -> `no_local_vc_signature`

Bugs:
- `agg_sig_db` -> `bug_aggregation_error`
- `duty_db` -> `bug_duty_db_error`
- `fetcher_error` -> `bug_fetch_error `

**Comment by gsora** [comment]
Closed by https://github.com/ObolNetwork/charon/pull/3033
