### ISSUE TITLE
Create an aggregate uptime dashboard

### ISSUE THREAD

**Issue by aly-obol** [ObolNetwork/charon#2498]
As part of improving the platform OKRs tracking, we need to create an aggregate grafana dashboard to report the uptime for our critical services (Relays, LP, and API)

**Comment by boulder225** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2498?planning-poker) with Zenhub @aly-obol

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2498?planning-poker) with Zenhub @LukeHackett12 @sugh01 @haroldsphinx

**Comment by corverroos** [comment]
Not sure this is related to charon...
