### ISSUE TITLE
Align logs with level guidelines.

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2499]
# 🎯 Problem to be solved
There are some error and warning logs that are not aligned with the [guidelines](https://github.com/ObolNetwork/charon/blob/main/docs/goguidelines.md):
```
The following log levels are used:
- error: Critical failures that require human intervention. [almost never used]
- warn: Important failures that do not require human intervention. [rarely used]
- info: Info logs describe the outcomes of high level process or critical information very valuable to the user. [seldom used]
- debug: Debug logs describe important steps within a process. Each process may only log a few of these. [sometimes used]
```

# 🛠️ Proposed solution
Review each error log, and change most to warns.
Review each warn log and change a few to info

Remove noisy log value logs. Remove logging fields that do not add concrete value.

Change the error rate health check from warning to critical.

**Comment by boulder225** [comment]
we use the right log level
