### ISSUE TITLE
Add more VC to compose smoke tests

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2501]
# 🎯 Problem to be solved
We only test teku in our compose smoke tests. This doesn't provide any testing for other VC types. 

# 🛠️ Proposed solution
Add at least 2 more VCs to compose smoke tests.
It probably makes sense to define a set of tests for an "abstract VC", then create a table test for each vc type. So one can just add VCs to that slice. (after adding support for that VC).

**Comment by dB2510** [comment]
@corverroos We have smoke tests with vouch and lodestar. But yeah we need to add matrix tests to test all scenarios with all supported VC combos.
