### ISSUE TITLE
Remove Priority protocol 

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2502]
# 🎯 Problem to be solved
The priority protocol isn't being used for anything. It has been six months and no use-cases have become apparent. It is best practice to remove code that doesn't add actual value. One can always re-add it later if required.

# 🛠️ Proposed solution
Remove the priority protocol, infosync, and mutableconfig.

**Comment by boulder225** [comment]
moving back to parking lot since it is not the major priority anymore.
