### ISSUE TITLE
Prevent the processing of incomplete data packets during DKG

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2513]
## 🎯 Problem to be solved
During the Exchanger refactor, an oversight occurred where a check was omitted. This omission allows incomplete data packets during DKG (Distributed Key Generation) to be processed. This could lead to potential errors or vulnerabilities within the system, impacting the integrity of the key generation process.

## 🛠️ Proposed solution
We need to reintroduce the omitted check into the Exchanger code to resolve this issue. The proposed steps include:

1. **Identify the Check**: Review the previous versions of the Exchanger code to identify the omitted check that prevented the processing of incomplete data packets.

2. **Implement the Check**: Re-implement the identified check in the current version of the Exchanger, ensuring that handles incomplete data packets during DKG.

3. **Testing**: test the updated code with different scenarios, including cases with incomplete data packets, to ensure that the reintroduced check works as expected.

4. **Monitoring and Follow-up**: Monitor the system after deployment to detect any unexpected behavior or issues and make necessary adjustments.

By implementing and testing the reintroduction of this check, we can ensure that the Exchanger component prevents the processing of incomplete data packets during DKG, maintaining the overall security and integrity of the system.

**Comment by gsora** [comment]
Fixed by https://github.com/ObolNetwork/charon/pull/2510
