### ISSUE TITLE
Release using go-releaser

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2540]
# 🎯 Problem to be solved
We currently only release docker images which are built by github actions.

There are a few limitations to this approach:
- When building locally from source with `go build`,  the app version is incorrect, it needs to be set via ldflags, see #2453.
- Users have requested other artefacts than docker containers, like binaries, see #759.

# 🛠️ Proposed solution
Use [go-releaser](https://goreleaser.com/) to solve all the release problems and to support best practices.

- It supports setting ldflags via the `.go-releaser.yml` file.
- Building from source is therefore as simple as `goreleaser release --snapshot --clean`
- Use can be used to build a matrix of OS and Architecture docker images.
- It can be used to build signed binaries

Note I suggest we tag `main` commits with `dev` and official releases with `latest`.

**Comment by gsora** [comment]
We benched goreleaser since cross-compiling from a single architecture with cgo is not an easy task. Users can self-compile a binary by using the `Makefile` we now provide.
