### ISSUE TITLE
add new libp2p metrics to relay

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#2544]
# 🎯 Problem to be solved
libp2p added a bunch of new circuit [relay metrics](https://github.com/libp2p/go-libp2p/pull/2154) as part of there v0.27.0 release. We should instrument these to make detecting issues with relay easier for operators.

# 🛠️ Proposed solution
Determine which metrics to enable and enable it.

**Comment by gsora** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2544?planning-poker) with Zenhub @KaloyanTanev @pinebit
