### ISSUE TITLE
build a compatibility matrix detailing "supported BN vs VC versions"

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2557]
## 🎯 Problem to be solved
There's an incompatibility between certain versions of Teku VC and Lighthouse BN. This is causing the error: "Details: Missing value for spec constant 'GOSSIP_MAX_SIZE'." Additionally, there's a lack of clarity regarding which versions are compatible due to the absence of a compatibility matrix or documentation detailing "supported BN vs VC versions".

## 🛠️ Proposed solution
- [ ] Create/update a clear compatibility matrix or document detailing the supported BN vs VC versions to prevent such issues in the future.
- [ ] Ensure that users know Teku VC 23.6.0 is compatible with Lighthouse BN v4.2.0, as a temporary solution until newer versions become compatible.

URLs:
- [Lighthouse <> Teku Incompatibility Spreadsheet](https://docs.google.com/spreadsheets/d/1Le-6M8iff3A3GXO4PFb8S-jEjitiP3rwWrm2VPt8VsM/edit#gid=0)

**Comment by corverroos** [comment]
Where should this document be created? Should it only contain Lighthouse and Teku?

**Comment by boulder225** [comment]
I'd suggest extending our internal Clients Integrations Project Management board, and tracking the compatibility of the other clients as well.
