### ISSUE TITLE
Allow Minimal Config in Charon to allow integration with Hive

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon#2573]
# 🎯 Problem to be solved
To make Charon DV nodes to be able to run inside Hive, we would need to allow "Minimal" configuration in Charon.
Client implementations implement "Minimal" configuration for setting up devnets for testing purposes. We need to allow a similar configuration as Hive `minimal` config. The specs are below - 

`PRESET_BASE: mainnet
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: "64"
MIN_GENESIS_TIME: 1606824000
GENESIS_FORK_VERSION: "0x0000000a"
GENESIS_DELAY: 604800
ALTAIR_FORK_VERSION: "0x0100000a"
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: "0x0200000a"
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: "0x0300000a"
CAPELLA_FORK_EPOCH: 18446744073709551615
EIP4844_FORK_VERSION: "0x0400000a"
EIP4844_FORK_EPOCH: 18446744073709551615
TERMINAL_TOTAL_DIFFICULTY: "100"
TERMINAL_BLOCK_HASH: "0x0000000000000000000000000000000000000000000000000000000000000000"
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615
SECONDS_PER_SLOT: 6
SECONDS_PER_ETH1_BLOCK: "14"
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 0
SHARD_COMMITTEE_PERIOD: 0
ETH1_FOLLOW_DISTANCE: "1"
INACTIVITY_SCORE_BIAS: "4"
INACTIVITY_SCORE_RECOVERY_RATE: "16"
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: "4"
CHURN_LIMIT_QUOTIENT: "2"
PROPOSER_SCORE_BOOST: "40"
DEPOSIT_CHAIN_ID: "7"
DEPOSIT_NETWORK_ID: "7"
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242

The name of the Network is `Custom` - an example from the `bn logs` -
`Sep 07 05:58:46.597 INFO Logging to file                         path: "/data/beacon/beacon/logs/beacon.log"
Sep 07 05:58:46.598 INFO Lighthouse started                      version: Lighthouse/v4.3.0-1373dcf
Sep 07 05:58:46.598 INFO Configured for network                  name: custom (/data/testnet_setup)
Sep 07 05:58:46.599 INFO Data directory initialised              datadir: /data/beacon`

# 🛠️ Proposed solution
- [ ] Approved design doc: *link*
- [ ] Core team consensus on the proposed solution

Describe the solution to be implemented

# 🧪 Tests
- [ ] We should be able to run a Charon DV node inside hive, without having to change HIVe minimal config

**Comment by corverroos** [comment]
Charon isn't responsible for the the network spec, it just passes whatever the BN provides to the VC. So this is configured in the BN, not in Charon.

**Comment by sugh01** [comment]
okay let me check and revert
