### ISSUE TITLE
Revamp Platform Support & Incident Management Process

### ISSUE THREAD

**Issue by haroldsphinx** [ObolNetwork/charon#2585]
# 🎯 Problem to be solved

We need to revamp our Incident Management process Support process within the platform team to address the following concerns:
- Review of OnCall Rotation
- Escalation Policies & Runbooks Creation
- Managing Handoffs, Vacations & OOO
- How other teams should report an Incident ( e.g Trigering PagerDuty Incidents from slack)
- Cross team Incident Reponse Education
- Response Plays

# 🛠️ Proposed solution

- [ ]

**Comment by dB2510** [comment]
Hey @haroldsphinx 
How is this issue relevant to charon?
