### ISSUE TITLE
Implement deneb support

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2597]
# 🎯 Problem to be solved

Implement support for deneb.

# 🛠️ Proposed solution
- [x] Approved design doc: https://docs.google.com/document/d/1WcJ4P-_JO937biy4nzwrYyWrYapldiTlAyOQU0qoCo0/edit#heading=h.yhsadc1regoc
- [x] Core team consensus on the proposed solution

Implement solution 2

# 🧪 Tests

We need to test deneb support on devnets: https://github.com/ethpandaops/dencun-testnet

Also, see https://dencun-devnet-8.ethpandaops.io/

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2597?planning-poker) with Zenhub @gsora @dB2510 @xenowits

**Comment by xenowits** [comment]
Closing this as changes to core interfaces is merged now
