### ISSUE TITLE
Stafi integration

### ISSUE THREAD

**Issue by samparsky** [ObolNetwork/charon#2631]
## 🎯 Problem to be solved

The integration of Obol into StaFi LSTs introduces several challenges:

- **Integration Complexity:** The integration of Obol into StaFi's liquid staking token (LST) protocol requires a connection between the two systems, ensuring cluster creation, operator interaction, and reward management.

- **Stability and Security:** The operator's operation's stability and slashing prevention are crucial. A collateral requirement for the operator ensures their commitment to secure operation. 

- **Withdrawal Mechanism:** Implementing a withdrawal mechanism using Obol manager contracts is crucial to handle partial and full withdrawals.

- **Decentralization:** Integrating Obol should enhance decentralization. Trust validators should be minimized and only used as a backup.

- **Reward Token (rETH):** The integration should enable rETH stakers to generate corresponding rETH.

- **Risks and Slashing:** There are risks associated with off-chain service operation, including server failures and centralization concerns

## 🛠️ Proposed solution

Design doc: https://www.notion.so/Discussion-Draft-Proposal-Integration-of-Obol-into-StaFi-LSTs-8736c144e9244360bbccdace320094a7

**Comment by boulder225** [comment]
clone of https://github.com/ObolNetwork/obol-manager-contracts/issues/100

**Comment by dB2510** [comment]
Irrelevant to charon
