### ISSUE TITLE
remove v0.99 version to avoid confusion

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2655]
# 🎯 Problem to be solved
Confusion exists around the `v0.99` tag in the Charon GitHub releases. This tag, which was created for testing compile-time tagging, has led to complications in the release process.

## 🛠️ Proposed solution
- [x] Remove the `v0.99` tag from GitHub to avoid further confusion.
- [x] Revise and document the tagging and release process to make it more transparent and less prone to errors.
- [x] Review and refine `genchangelog` script to ensure it only takes major releases into account.

**Comment by gsora** [comment]
> Review and refine genchangelog script to ensure it only takes major releases into account.

https://github.com/ObolNetwork/charon/pull/2652 takes care of that
