### ISSUE TITLE
implement a threshold-based recombination

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2663]
# 🎯 Problem to be solved
The current key recombining process requires all key shares to be present, contradicting the resilience feature of DVT  as suggested in the [docs](https://docs.obol.tech/docs/int/quickstart/advanced/quickstart-combine). The [CLI reference](https://docs.obol.tech/docs/charon/charon-cli-reference#the-combine-subcommand) mentions all key shares need to be present. 

`09:11:50.294 ERRO cmd     Fatal error: not all private key shares found for validator {"validator_index": 0, "expected": 4, "actual": 3}`

## 🛠️ Proposed solution
- [ ] Research how to implement a threshold-based recombination instead of requiring all key shares.
- [ ] Conduct a risk assessment to weigh the trade-offs between resilience and the potential for collusion.
- [ ] Update documentation to reflect any changes made.

**Comment by dB2510** [comment]
Closed by #2664
