### ISSUE TITLE
fix synthetic proposal when block not found

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2695]
# 🎯 Problem to be solved

Fix synthetic proposal errors when beacon block for a slot is not found
```
Permanent failure calling fetcher/fetch: fetch builder proposer data: beacon api signed_beacon_block: GET failed with status 404: {"code":404,"message":"NOT_FOUND: beacon block at slot 6917368","stacktraces":[]} {"label": "signed_beacon_block", "duty": "6917369/builder_proposer"}
```

# 🛠️ Proposed solution

If a not found error is received (404), continue looking for blocks in earlier slots until found instead of erroring.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by dB2510** [comment]
Fixed by #2702
