### ISSUE TITLE
Update charon to comply with go-eth2-client v0.19.5

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2708]
# 🎯 Problem to be solved

We need to update charon to comply with recent changes in go-eth2-client version v0.19.5.

The dependabot PR for the upgrade is failing for the same reason: https://github.com/ObolNetwork/charon/pull/2706.

# 🛠️ Proposed solution

Update code and fix tests so that new version of go-eth2-client dependency integrates perfectly with charon.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by dB2510** [comment]
Completed by #2709
