### ISSUE TITLE
Return dependent root from validatorapi

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#2736]
# 🎯 Problem to be solved
We need to return a [proper](https://github.com/ObolNetwork/charon/blob/cb4c265a6c3d85da14f701c6da3f74a96e86a614/core/validatorapi/router.go#L469) `dependent_root` field as response to the duties endpoints. This is causing lodestar to flood WARN logs every slot:

```
Potential current epoch attester duties reorg slot=408896, dutyEpoch=12778, priorDependentRoot=0xea63000000000000000000000000000000000000000000000000000000000000
```

# 🛠️ Proposed solution
As part of recent go-eth2-client upgrade, it has started returning the `dependent_root` field as part of metadata which was absent in earlier versions. We need to add support of this field while returning response through validatorapi for VCs.
https://github.com/attestantio/go-eth2-client/blob/677e48992f5edabadc5acbaf11b8db654ac47c07/http/attesterduties.go#L84

# 🧪 Tests
- [x] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [x] Manually tested on local compose simnet

**Comment by boulder225** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2736?planning-poker) with Zenhub @pinebit
