### ISSUE TITLE
Analyze QBFT internal test intermittent failures 

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2747]
## 🎯 Problem to be solved
QBFT internal test in `qbft_internal_test.go` is failing intermittently, potentially due to timing issues within the CI environment. This is causing inconsistencies in test outcomes, specifically in consensus algorithm tests where QBFT employs timeouts.

```
        qbft_internal_test.go:67: 
            	Error Trace:	/home/runner/work/charon/charon/core/qbft/qbft_internal_test.go:439
            	            				/home/runner/work/charon/charon/core/qbft/qbft_internal_test.go:67
            	Error:      	Not equal: 
            	            	expected: int(2)
            	            	actual  : int64(3)
            	Test:       	TestQBFT/leader_down_const
```

## 🛠️ Proposed solution
- [ ] Analyze the QBFT internal test, focusing on its sensitivity to timing and timeouts.
- [ ] Review the QBFT paper to understand improvements in the test or the algorithm.

**Comment by dB2510** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2747?planning-poker) with Zenhub @dB2510 @gsora @pinebit @xenowits
