### ISSUE TITLE
Add failing registrations as a health check

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2760]
## 🎯 Problem to be solved

Currently, users experiencing high validator registration failures don't have a way to monitor these.

The health checks in charon is a good way to report such problems to our users.

## 🛠️ Proposed solution

- [ ] Add a new health check `high_registration_failure_rate` to the `app/check` package
- [ ] Trigger a `warning` severity level if `>= 70%` of registrations fail in an epoch

## Tests

Simulate high registration failure rate and check if the health check reports properly in local simnets.

In happy case, you should expect:
<img width="303" alt="Screenshot 2024-02-06 at 21 22 00" src="https://github.com/ObolNetwork/charon/assets/43061995/3226bec4-ebdf-471f-9b15-ae348c0aedef">

In case of high failure rate, expect this instead (`high_registration_failure_rate : warning`)
<img width="298" alt="Screenshot 2024-02-06 at 21 22 20" src="https://github.com/ObolNetwork/charon/assets/43061995/7485f1a9-b25d-4d98-ab36-276c1914ff3b">

**Comment by dB2510** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2760?planning-poker) with Zenhub @dB2510 @gsora @pinebit @xenowits

**Comment by pinebit** [comment]
Done.
