### ISSUE TITLE
Make Charon compatible with the Deneb hardfork (January 17th)

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2771]
## 🎯 Problem to be solved
Goerli testnet is undergoing a hardfork for Deneb scheduled on January 17th. 

## 🛠️ Proposed solution
- [x] test a Charon release compatible with the Deneb hardfork.
- [x] Ensure the release is ready before the hardfork date.
- [x] Conduct thorough testing to confirm compatibility and functionality.

**Comment by xenowits** [comment]
This is complete ✅
