### ISSUE TITLE
Feature to use extra CL clients as fallbacks rather than simultaneously

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#2787]
# 🎯 Problem to be solved

A user setup charon to point at two CLs in case the first one went down. Charon when given two CLs hits both and uses the fastest answer. This user would have been happier had there been a way to use the extra CLs as fallbacks only. 

# 🛠️ Proposed solution

Create a `--beacon-node-fallback-endpoints` flag on `charon run` that takes a list of consensus clients, and use them only when the endpoints in the `--beacon-node-endpoints` are all unhealthy. 

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by pinebit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2787?planning-poker) with Zenhub @KaloyanTanev @gsora

**Comment by OisinKyne** [comment]
Closing as duplicate of #3328
