### ISSUE TITLE
Update The `Licensed Work`  to reflect the current year

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2794]
## 🎯 Problem to be solved
- The `Licensed Work` currently displays `© 2022-2023 Obol Labs, Inc.` which needs to be updated to reflect the current year.

## 🛠️ Proposed solution
- [x] Identify all instances in the codebase where © 2022-2023 Obol Labs, Inc. is mentioned.
- [x] Update each instance to © 2024 Obol Labs, Inc.

**Comment by pinebit** [comment]
https://github.com/ObolNetwork/charon/pull/2836
