### ISSUE TITLE
Investigate potential memory leak

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2835]
# 🎯 Problem to be solved

One node in one of our clusters (`Obol Mainnet #1/careful-rocket`) is experiencing high memory usage.

<img width="951" alt="Screenshot 2024-01-29 at 14 22 51" src="https://github.com/ObolNetwork/charon/assets/43061995/4666382d-5227-4873-b03f-2dfcfa66dfcc">

We need to investigate into this.

# 🛠️ Proposed solution

This may be caused by a potential memory leak. Use pprof files to visualize points of high memory usage.

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by gsora** [comment]
It was due to Teku using the new `POST` method for the `get_validator` endpoint.

Was fixed already in `main`, will be fixed for public release on version `v0.19.1`.
