### ISSUE TITLE
Implement POST get validators endpoint

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2840]
# 🎯 Problem to be solved

A [new](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/postStateValidators) endpoint has been recently added to the `beacon APIs` to query validators from the beacon chain
```
POST /eth/v1/beacon/states/{state_id}/validators
```

Note that we already have an endpoint for the same purpose of querying validators, but it's a `GET` that takes in validator pubkeys/indices in a query parameter
```
GET /eth/v1/beacon/states/{state_id}/validators
```

# 🛠️ Proposed solution

Implement the new POST endpoint in `core/validatorapi`.

This will probably require us to read the bytes in the request body (`router.go`):
```
...
func getValidators(p eth2client.ValidatorsProvider) handlerFunc {
	return func(ctx context.Context, params map[string]string, query url.Values, _ contentType, _ []byte) (any, http.Header, error) {
		stateID := params["state_id"]

		resp, err := getValidatorsByID(ctx, p, stateID, getValidatorIDs(query)...)
...
```

So, one approach might be to:
1. Read query parameters for validator pubkeys/indices
2. If no query parameters provided, read request body
3. If query parameters provided, don't read request body

# 🧪 Tests
- [x] Tested by new automated unit/integration/smoke tests
- [x] Manually tested on core team/canary/test clusters
- [x] Manually tested on local compose simnet

**Comment by dB2510** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2840?planning-poker) with Zenhub @dB2510 @gsora @pinebit @xenowits

**Comment by pinebit** [comment]
Tested
