### ISSUE TITLE
Sync aggregations support with prysm

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2841]
# 🎯 Problem to be solved

We want to support aggregation duties for prysm validator client. Recently prysm added support for beacon REST APIs. As a result of this, we can now add support aggregate selection endpoint to `prysm` validator client. Recently our testnet operators have also asked for prysm support like kraken.

We have already [added](https://github.com/ObolNetwork/charon/issues/2231) support for `beacon committee selections` to prysm VC.

Next up, implement `sync committee selections` in prysm.

# 🛠️ Proposed solution
 - Add support for sync aggregation duties to prysm by adding sync selection endpoints.
 - This ticket is a proxy for the current open ticket on prysm: https://github.com/prysmaticlabs/prysm/issues/11985 .

# 🧪 Tests
- [ ] Manually tested on core team/canary/test clusters

# 👐 Additional acceptance criteria
All successful duties except builder-proposer on testnet.

# ❌ Out of Scope
Adding prysm VC to compose.

**Comment by dB2510** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2841?planning-poker) with Zenhub @dB2510 @pinebit @xenowits @gsora
