### ISSUE TITLE
Integrate 'statuses' Query Parameter Support in getValidators Function

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2846]
## 🎯 Problem to be solved
`getValidators` function does not fully align with the specs, as it only reads `ids` from the query parameters, while the spec mentions both `ids` and `statuses`. The `go-eth2-client` library, which we depend on, does not support `statuses` as a query parameter. This discrepancy could limit our validator API, potentially missing out on filtering.

## 🛠️ Proposed solution
- [ ] Support `go-eth2-client` project by proposing a PR supporting `statuses`.
- [ ] For now, have TODOs in our codebase to integrate `statuses` parameter support once it becomes available in the go-eth2-client library.

**Comment by pinebit** [comment]
Blocked by https://github.com/attestantio/go-eth2-client/issues/103

**Comment by pinebit** [comment]
Confirmed with attestant: once this API gets stable and supported by various clients, we can take it into development.

**Comment by pinebit** [comment]
This ticket is ready to go, but it requires the new version of the go-eth2-client, which is to be integrated under #2936

**Comment by pinebit** [comment]
We probably don't need this.
