### ISSUE TITLE
Test partial deposits flow in create cluster

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2847]
# 🎯 Problem to be solved

We have fully [implemented](https://github.com/ObolNetwork/charon/issues/2728) the [partial deposits](https://docs.google.com/document/d/1S2HrktE8IXvY6hika8pWPbzMiACbRobEONL1l7El4c4/edit#heading=h.alakie8lxcfb) feature under the `create cluster` command. As part of the implementation, we have ensured that only minimal changes are introduced so we can easily test this feature and gather proper feedback from our customers.

# 🛠️ Proposed solution

We now need to test the `partial deposits` feature. This includes:
* Test if create cluster command properly creates correct cluster definitions
* Write sufficient unit/integration tests to verify the whole flow
* Manually create cluster and provide different inputs

# 🧪 Tests

None.

**Comment by pinebit** [comment]
Validation works as expected:
```
$ charon create cluster --nodes 4 --network goerli --num-validators 1 --deposit-amounts=1,7,16,9 --fee-recipient-addresses=0xC730155a5F702B6bF3CaeCD2
5ebff9fB1b2a2B85 --withdrawal-addresses=0xC730155a5F702B6bF3CaeCD25ebff9fB1b2a2B85
13:03:05.430 ERRO cmd        Fatal error: sum of partial deposit amounts must sum up to 32ETH {"sum": 33000000000}
```

Proper partial amounts generate proper deposit files.
