### ISSUE TITLE
Migrate core team cluster to holesky

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#2858]
# 🎯 Problem to be solved

The core team cluster is currently running on `goerli` which is going to be `deprecated` in about 2 months.

# 🛠️ Proposed solution

Migrate the core team cluster from `goerli` to `holesky` networks.

* **Exit** the existing goerli validators
* **Activate** 100 validators on holesky for this cluster
* **Create** a new cluster definition for the holesky network with 100 DVs
* **Document** the steps for this migration

# 🧪 Tests

- [ ] Manually tested on core team/canary/test clusters

**Comment by boulder225** [comment]
we are going to shutdown the cluster.
