### ISSUE TITLE
Handle gracefully DKG requests from banned IP ranges

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2897]
## 🎯 Problem to be solved
- There are issues with users trying to use the API and DKG from banned IP ranges, which leads to errors when HTML is fed into the JSON decoder due to Cloudfare blocking the requests. This issue occurred when creating a DKG for a launchpad, where the error indicated an attempt to parse HTML as JSON, suggesting Cloudfare had blocked access.

## 🛠️ Proposed solution
- [ ] Investigate the handling of HTTP status codes related to redirection or blocking by Cloudfare, specifically looking into managing 300-range codes.
- [ ] Implement more graceful error handling for non-200 HTTP responses to ensure that the system does not attempt to parse HTML as JSON.

**Comment by gsora** [comment]
Fixed by #2898
