### ISSUE TITLE
Draft Dappnode PRD

### ISSUE THREAD

**Issue by sugh01** [ObolNetwork/charon#2921]
Draft PRD from the following wishlist

Requirements have been gathered:

```
1. Better support for uploading .charon files, to integrate DKG.
2. Introduction of deeplinks to the built-in Grafana for monitoring
3. Aggregation support
4. Integration with Web3Signer for secure key management (see ConsenSys doc)
5. `--publish` flag for automated service publishing
6. A direct link to the cluster status page for real-time dappnode monitoring
7. Holesky package for dappnode
8. Re-enabling the dappnode tab on the launchpad DKG screen
9. documentation page for dappnode IPFS hashes
10. pentest after implementing the wishlist items.
11. check multi-lingual support
12. list of org members who have dappnode,  to distribute VPN access
13. Flexibility and resilience to support dynamic network configurations.
```

Next Steps:
1) Analyze and see what it needs to make it run inside Dappnode
2) Analyze what is needed from the Dappnode team to collaborate (Ideally we would like to collaborate to their core engine but will check that later)
3) Add User acceptance scenarios
4) Validate with stakeholders

**Comment by OisinKyne** [comment]
Should tackle `--force` / unclean shutdown issues, either automatically or when a user intervenes by clicking a button on the package.

**Comment by gsora** [comment]
I wonder if Charon should output json logs when deployed through dappnode, so their software can easily parse it.
