### ISSUE TITLE
Obol 0.19.X brakes our cluster

### ISSUE THREAD

**Issue by AutoStake-com** [ObolNetwork/charon#2945]
# 🐞 Bug Report

### Description

Hey whenever trying to upgrade from obol 0.18.0 to obol 0.19.X
I get these errors and validators stop signing

{"level":"warn","service":"client","impl":"http","id":"51f539b1","address":"http://teku-rpc:5051","endpoint":"/eth/v2/debug/beacon/states/head","status_code":200,"error":"context deadline exceeded","time":"2024-03-05T13:29:01+01:00","message":"Failed to read body"}

{"level":"warn","service":"client","impl":"http","id":"234bf840","address":"http://lighthouse-rpc:5052","endpoint":"/eth/v2/debug/beacon/states/head","status_code":200,"error":"context deadline exceeded","time":"2024-03-05T13:29:01+01:00","message":"Failed to read body"}

{"level":"warn","service":"client","impl":"http","id":"79689862","address":"http://nimbus-rpc:5052","endpoint":"/eth/v2/debug/beacon/states/head","status_code":200,"error":"context deadline exceeded","time":"2024-03-05T13:29:01+01:00","message":"Failed to read body"}

13:29:01.002 WARN sched      Resolving duties error (retrying next slot): beacon api validators: failed to read body: context deadline exceeded {"slot": 8568143, "label": "validators"}
    app/eth2wrap/eth2wrap.go:367 .wrapError
    app/eth2wrap/eth2wrap_gen.go:667 .Validators
    core/scheduler/scheduler.go:643 .resolveActiveValidators
    core/scheduler/scheduler.go:250 .resolveDuties
    core/scheduler/scheduler.go:177 .scheduleSlot
    core/scheduler/scheduler.go:123 .Run
    app/lifecycle/hook.go:41 .Call
    app/lifecycle/hook.go:131 .startHook
    app/lifecycle/hook.go:160 .func2
 
endpoint: /eth/v2/debug/beacon/states/head
status_code: 200
but
error: failed to read body: context deadline exceeded 

Reverting to v0.18.0 still works flawlessly  again

### Has this worked before in a previous version?

 Yes, the previous version in which this bug was not present was: 0.18.0

## 🔬 Minimal Reproduction

Docker cluster with 4 different beacon docker all on the latest version of each BN's, EN's and VC's, Charon 0.18.0 still works

## 🔥 Error

{"level":"warn","service":"client","impl":"http","id":"79689862","address":"http://nimbus-rpc:5052","endpoint":"/eth/v2/debug/beacon/states/head","status_code":200,"error":"context deadline exceeded","time":"2024-03-05T13:29:01+01:00","message":"Failed to read body"}

13:29:01.002 WARN sched      Resolving duties error (retrying next slot): beacon api validators: failed to read body: context deadline exceeded {"slot": 8568143, "label": "validators"}

## 🌍  Your Environment

**Operating System:**

Seperate Debian 11 servers + Docker, with charon ping times under 100ms on 0.18.0

**What version of Charon are you running? (Which release)**

0.18.0 - Works
0.19.0 - Broken
0.19.1 - Broken

**Comment by AutoStake-com** [comment]
1000 potential validators, only 5 in use currently though

**Comment by AutoStake-com** [comment]
> Hi! How many validators does your cluster contains? We’ve been debugging a similar issues in our internal test clusters. This problem is related to a dependency we use to speak with the beacon node API, and usually manifests itself if a cluster has more than 150 validators.

1000 validators keys, only 5 in use currently though

**Comment by AutoStake-com** [comment]
It seem the prysm BN has a slight different error:

13:50:11.000 WARN sched      Resolving duties error (retrying next slot): beacon api validators: nok http response {"slot": 8568549, "label": "validators", "status_code": 404, "endpoint": "/eth/v2/debug/beacon/states/head", "method": "GET", "data": "404 page not found\n"}

It actually produces a 404 instead of 200 and timeout

**Comment by gsora** [comment]
Interesting, this is issue then is probably related to the issue we’re triaging. We will release a new version of Charon with a fix hopefully in the next few days or hours.

**Comment by AutoStake-com** [comment]
> Interesting, this is issue then is probably related to the issue we’re triaging. We will release a new version of Charon with a fix hopefully in the next few days or hours.

Thank you so much for your replies! we were starting to panic over here :)

**Comment by AutoStake-com** [comment]
> Interesting, this is issue then is probably related to the issue we’re triaging. We will release a new version of Charon with a fix hopefully in the next few days or hours.

Is this going to be released before the 13th? :crossed_fingers:

**Comment by gsora** [comment]
Hi! We tagged v0.19.2 on Friday. While the release will only be announced on Monday you can grab the docker image from the docker hub and give it a try in the meantime!

**Comment by AutoStake-com** [comment]
> Hi! We tagged v0.19.2 on Friday. While the release will only be announced on Monday you can grab the docker image from the docker hub and give it a try in the meantime!

Thank you! 
I didn't see that, should have checked, sorry!

**Comment by AutoStake-com** [comment]
Confirming v0.19.2 resolved our issue :partying_face: 

Officially Dencun ready

Thank you so much!
