### ISSUE TITLE
Implement Peer-to-Peer Connection Tests

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#2997]
## 🎯 Problem to be solved
Verify the connectivity and health of peer-to-peer connections within the Charon cluster.

## 🛠️ Proposed solution
- [ ] Start libp2p node, connect to relay and subsequently to other libp2p nodes
- [ ] Implement a test to check if our node can ping all other nodes
- [ ] Implement a test to measure packet loss between peers
- [ ] Implement a test to measure round-trip time (RTT) between peers
- [ ] Accumulate and evaluate the peer-to-peer connection test results, contributing to the overall cluster health assessment
- [ ] Include the peer-to-peer connection test results in the report

**Comment by KaloyanTanev** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/2997?planning-poker) with Zenhub @pinebit @gsora
