### ISSUE TITLE
Design Consensus Abstraction

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3034]
## 🎯 Problem to be solved
The integration of more protocols than QBFT requires the consensus layer abstraction (devising a common interface to all present and future BFT implementations, making Charon itself fully agnostic to specific implementations). This demands a solution that incorporates node participation proof, efficient duty consensus, and adaptable leader election. A design document is essential to ensure the effectiveness and cohesiveness of this integration.

## 🛠️ Proposed solution
- [ ] Draft a design document outlining the architecture of the consensus abstraction layer, which acts as a bridge between multiple protocols. This document will define the system's architecture, including data flows, module interfaces, and interaction mechanisms between protocols.
- [ ] The document will include a modular strategy for protocol feature selection, allowing customization based on network conditions and specific consensus requirements.

**Comment by pinebit** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3034?planning-poker) with Zenhub @gsora @KaloyanTanev

**Comment by boulder225** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3034?planning-poker) with Zenhub @pinebit
