### ISSUE TITLE
Improve the unit testing suite for test peers command

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3064]
## 🎯 Problem to be solved

Improve the testing suite for test peers command. Currently the unit test suite does not perform the actual tests ran by the command.

## 🛠️ Proposed solution

- [ ] Spin up local relay to which nodes connect
- [ ] Spin up 2 (or more) nodes that run the test cases against each other

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3064?planning-poker) with Zenhub @pinebit @KaloyanTanev @gsora

**Comment by gsora** [comment]
Can we have more context on this ticket?

**Comment by KaloyanTanev** [comment]
Where is this one coming from? I'd suggest from now on we have tickets for exact test cases we want to add. I suppose this one is regarding the direct connection between peers test that I am working on. If that's the case, let me know, so I can add more details to the ticket. @boulder225
