### ISSUE TITLE
Test if Teku supports sync committee aggregations

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3067]
## 🎯 Problem to be solved
Test if the latest version of Teku client supports sync committee aggregations correctly.

Useful article: https://blog.obol.tech/committee-aggregations-with-distributed-validators/

## 🛠️ Proposed solution
- [x] Set up a test environment with  the latest release version of Teku client and configure it to include sync committee aggregations
- [x] Run tests to verify if sync committee aggregations are working as expected

**Comment by pinebit** [comment]
Teku implemented the DVT endpoints committee aggregations in according with the article: https://blog.obol.tech/committee-aggregations-with-distributed-validators

However, Teku fails while processing response to `POST /eth/v1/validator/beacon_committee_selections`, the error says it expects 64 entries while it is received 63. 
Other VC clients (except Prysm) are satisfied with the response. The conclusion here is that likely Teku needs a fix to make the implementation matching other clients (Lodestar/Lighthouse). If we continue investigating this by ourselves, we need to dive deeper into Teku code.
