### ISSUE TITLE
Core Cluster Revamp for Protocol Team Testing and Development

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3071]
## 🎯 Problem to be solved
Revamp the core cluster for the Protocol team to serve as a testing and development environment.

## 🛠️ Proposed solution
- [ ] Determine the required number of validators for the core cluster (e.g., 500 validators as discussed).
- [ ] Secure the necessary amount of Holesky ETH to activate the validators (e.g., 16K Holesky ETH for 500 validators).
- [ ] Provision cloud instances or set up Dappnodes to run the cluster nodes.
- [ ] Ensure each team member has an Ethereum wallet to sign acceptance messages and participate in the cluster creation process.
- [ ] Decide on the client version to run (e.g. RC, or a specific version for testing purposes).
- [ ] Plan for testing scenarios like partial deposits, cluster recovery, etc.
- [ ] Document the process of setting up the cluster, including steps for creating cloud instances, configuring nodes, depositing validators, etc.

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3071?planning-poker) with Zenhub @gsora @KaloyanTanev @pinebit

**Comment by gsora** [comment]
ATM we're missing ~3K holeskyETH to proceed with the core cluster.
