### ISSUE TITLE
Investigate and fix sync committtee aggregations

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3080]
## 🎯 Problem to be solved
This ticket follows the investigation already happened in https://app.zenhub.com/workspaces/obol-workspace-648c1170ee94656741353327/issues/gh/obolnetwork/charon/3067 

Investigate and resolve the issue with the committee aggregation failing when querying endpoints designed for distributed validator clients (DVCs) like Teku. This seems to be the only duty not supported by the latest Teku version.

## 🛠️ Proposed solution
- [x] Reproduce the issue locally with Teku and document the steps to recreate it.
- [x] Investigate the root cause of the issue, which appears to be a mismatch between the expected and received number of entries in the response from the DVT endpoint.
- [x] Review the Teku codebase and the DVT implementation to understand the expected behavior and any potential changes or optimizations made in the latest version.
- [x] Consult the Teku documentation 
- [x] Analyze the logs and error messages from both Teku and the client

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3080?planning-poker) with Zenhub @gsora @KaloyanTanev @pinebit

**Comment by pinebit** [comment]
Having a deep dive into Teku/Lodestar and charon, together with the initial design of this feature I must conclude we have a bug in Charon, specifically in https://github.com/ObolNetwork/charon/blob/a50b2c006a38496ab555e2a7aafae03eb2a1be5e/core/validatorapi/validatorapi.go#L843

This functions receives a slice of selections that may include many subcommittee indices for the same slot/pubkey combination. Our implementation iterates over this selections slice and rewrites the previous `PartialSignedSyncCommitteeSelection`, for the last entry of the given selections. Then it runs aggregation round for this and only this entry. The resulting output is of length = 1, whereas Lodestar/Teku expect the number of entries equal to the input selections.

Lodestar is more forgiving, it yields warning for the missing aggregations and proceeds with the one received.
Teku is not forgiving, it throws an exception `ObolDvtIntegrationException: Missing selection proof for validator_index =...`, does not proceed with publishing even for valid entries.

I believe in charon, we need to run as many aggregation rounds as many input selections we received.

**Comment by pinebit** [comment]
The issue seems gone after we increased number of validators to 512 in kurtosis.
Here is the dashboard: https://grafana.monitoring.gcp.obol.tech/d/b962e704-2e37-48a4-82c0-b15d7661e8a6/charon-overview-v3-testnet-updates?orgId=1&var-cluster_network=testnet&var-cluster_name=test&var-cluster_hash=d0d9162&var-cluster_peer=encouraging-pen&var-job=charon-1&var-peer=All&var-interval=$__auto_interval_interval&var-duty=All&refresh=10s
(rewind to the time of this comment to see the data)

**Comment by pinebit** [comment]
No issues observed within four hours. Considering the latest Teku as working fine.
