### ISSUE TITLE
Presign Exit by validator index

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#3104]
# 🎯 Problem to be solved

Right now you must exit a validator by its `distributed_validator_public_key`, this can be confusing as it is not the public key of the partial nor is it the same name as the flag in this command `--validator-public-key`. Most humans can parse the 6/7 digit validator index much more effectively than the BLS pubkey for valdiators, and I think it would be more convenient to handle and reason about when using these exit commands. 

# 🛠️ Proposed solution

It might be a big ux improvement to also add `--validator-index` as an alternative to `--validator-public-key`. 

Technically we might even be able to skip the `beacon-node-url` flag from `charon exit sign` if it was only being used to retrieve the state/index anyways.  (While i write this, is there any chance we can edit this/alias the `beacon-node-url` flag to be `beacon-node-endpoints` like `charon run`? can imagine lots of people being caught by that gotcha otherwise, imo we should favour consistency. 

- [ ] Core team consensus on the proposed solution

Describe the solution to be implemented

# 🧪 Tests
- [ ] Tested by new automated unit/integration/smoke tests
- [ ] Manually tested on core team/canary/test clusters
- [ ] Manually tested on local compose simnet

**Comment by gsora** [comment]
LFTM.

Should we do this by v1?

**Comment by OisinKyne** [comment]
yeah may as well?

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3104?planning-poker) with Zenhub @gsora @KaloyanTanev @pinebit
