### ISSUE TITLE
Build and test unstable branch of Nimbus for blocks production in Kurtosis

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3105]
## 🎯 Problem to be solved
The current releases of Nimbus (`24.4.0` and `24.5.1`) are not producing blocks when running as a Beacon Node in the Kurtosis testing environment.  

## 🛠️ Proposed solution
- [ ] Build the unstable branch of Nimbus, which reportedly includes a fix for the issue
- [ ] Test the unstable branch of Nimbus as a BN in the Kurtosis environment
- [ ] Verify that the unstable branch is correctly producing blocks
- [ ] If the unstable branch resolves the issue, continue testing and validating Nimbus as a BN using the unstable branch until a new stable release is available

**Comment by pinebit** [comment]
The issue has gone once we enforced JSON format via go-eth2-client. We will probably need to add a command line switch in Charon that will control this behavior.
For the purpose of this ticket everything is done, therefore closing.
