### ISSUE TITLE
Track vendor and version of the VCs used in our clusters

### ISSUE THREAD

**Issue by boulder225** [ObolNetwork/charon#3107]
## 🎯 Problem to be solved
There is a need to track the vendor and version information of the VCs used in our clusters. Currently, this information is not being tracked or monitored.

The natural idea is to track User-Agent header we receive in VAPI, e.g.
`"key": "User-Agent", "values": "nim-presto/0.0.3 (arm64/linux)"`

## 🛠️ Proposed solution
- [ ] Investigate the `User-Agent` header received in VAPI requests from different VCs to see if it contains reliable vendor and version information.
- [ ] If the `User-Agent` header provides the required information, implement a mechanism to extract and store the vendor and version details from the header.
- [ ] If the `User-Agent` header is not a reliable source, explore alternative methods to retrieve the vendor and version information from the VCs.
- [ ] Create a metric or monitoring system to track and display the vendor and version information of the VCs used in our clusters.
- [ ] Implement alerting or notification mechanisms if specific vendor or version combinations are encountered or if certain versions are outdated or known to have issues.

**Comment by boulder225** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Obol-Workspace-648c1170ee94656741353327/issues/ObolNetwork/charon/3107?planning-poker) with Zenhub @gsora @KaloyanTanev @pinebit

**Comment by pinebit** [comment]
Done with https://github.com/ObolNetwork/charon/pull/3112
