### ISSUE TITLE
Fixing Geth stakewise helm chart and our module Terraform beacon node

### ISSUE THREAD

**Issue by apham0001** [ObolNetwork/charon#3199]
Based on Geth documentation: --goerli, --holesky, --mainnet, and --sepolia are predefined networks, while --networkid is used for custom or other networks

**Comment by st1p3-obol** [comment]
becaon-node.tf, variables.tf and becaon-nodes-tf are all expecting `network`. 

When we have this ticket ready let me know and I can then merge my PR -> https://github.com/ObolNetwork/obol-infrastructure/pull/1283
