### ISSUE TITLE
Feature flag design proposal

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#381]
## Problem to be solved

Once we have released versions of charon running in the wild (public testnets), we need to be much more careful and controlled about how we rollout new features. Some features might be high risk, and we might want phase then in gradually over time (e.g. simnet only, then devnet, then testnet, and then mainnet). 

Some considerations:
 - We do not really have classic SaaS "environments" like dev, staging and prod.
 - We also do not really have a single linear set of "networks"/"chains" like devnet, testnet, prod.
 - There are a myriad of different "networks"/"chains" that charon can be deployed to: multiple testnets, gnosis chain, etc.
 - Some users might want to run "beta" features on mainnet.
 - Features should have a default "state", but this must be configurable via flags/config.
 - Be careful with flags, since they cannot be removed easily, see [prysm](https://github.com/prysmaticlabs/prysm/blob/develop/.github/ISSUE_TEMPLATE/feature_flag.md). 

## Proposed solution

- Introduce a new package/concept called `rollout`. 
- Features are "rolled out" in three [phases](https://en.wikipedia.org/wiki/Software_release_life_cycle): `alpha`, `beta`, `gold`.
- Features in `alpha` are unstable and only to be used/tested by the core team.
- Features in `beta` are more stable can be used/tested by the community (opt in), but still lacks confidence for general availability.
- Features in `gold` are stable and generally available.
- Package `rollout` enumerates a set of `Feature` strings that are each hardcoded to a `Phase`.
- Charon `run` command has a flag `--rollout` which defaults to `gold` but can be set to `alpha` or `beta`.
- This flag controls which features are active.
- Features are enabled/disabled in the code by simple `if` statements: `if rollout.Enabled(rollout.FeatureFoo) {`
- Features are rolled out by updating their hardcoded phase.
- The feature and check should be removed and permanently integrated/enabled after a full release in gold.
- Individual features can be enabled/disabled via a unstructured flag `--rollout-enable=csv,list,of,features` / `--rollout-disable`
- This flag just warns if features do not exist (or have been removed).

**Comment by corverroos** [comment]
Do we really need to split 100 lines of code into separate files? Feels a bit forced.

**Comment by leolara** [comment]
In general in go we separate by component or subcomponent subject not by number of lines
