### ISSUE TITLE
Slot and epoch should be uint64

### ISSUE THREAD

**Issue by leolara** [ObolNetwork/charon#383]
## Problem to be solved

The spec is that slot and epoch are uint64 (https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/#custom-types) however in some parts of our code they are int64. That forces us to be converting back and forth between types all the time.

## Proposed solution

Change the type to uint64 through

### Out of Scope

Anything not required to change the types

**Comment by corverroos** [comment]
Closing this for now since 2 months old
