### ISSUE TITLE
new component DutyResolver

### ISSUE THREAD

**Issue by leolara** [ObolNetwork/charon#395]
## Problem to be solved

Implementing the `validatorapi`/`Component.BeaconBlockProposal` we have realised that this endpoints needs to know the public key of a proposer for a given slot. This information is also required by the `Scheduler`, and currently it is resolved by it.

## Proposed solution

To make the validatorapi request this information to the Scheduler makes the architecture more cyclical and adds a responsability to the scheduler breaking SRP.

A new component that will serve the proposer and validator for each slot to both `validatorapi` and Scheduler.

This new component would implement the following interfaces:

```
interface AttestersResolver {
   AttesterDuties(ctx context.Context, slot phase0.Slot) (FetchArgSet, error)
}

interface ProposerResolver {
  ProposerDuties(ctx context.Context, slot phase0.Slot) (FetchArgSet, error)
}
```
> AttesterDuties will return an FetchArgSet of nil (if error) or 0..n
> ProposerDuties will return an FetchArgSet of nil (if error), 0 if no proposer or 1

This component will retrieve this information from the BN and store it in memory (and will be responsible to delete old ones in the future)

Both scheduler and validatorAPI will be able to request this information to this component without having to store it in memory themselves, making current scheduler code much simpler.

This task includes integrating with the scheduler, as it is basically moving some code from `scheduler.resolveDuties` into this new component.

### Out of Scope

Integrating into validatorAPI.

**Comment by corverroos** [comment]
Closing this for now since 2 months old
