### ISSUE TITLE
Refactor to use a create command with subcommands

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#442]
## Problem to be solved

To clean up the charon [command] output, we want to nest a number of subcommands under `charon create`. 

## Proposed solution

Add the following commands under `charon create`
- `enr`: Create an Ethereum Node Record private key to identify charon
- `dkg`: Create a charon DKG configuration file for `charon dkg`
- `cluster`: Create the configuration and private keys for a local cluster

### Out of Scope

The functions don't need to work for this ticket. They should just exist, have appropriate flags, perform appropriate validation, and error with meaningful errors.

**Comment by OisinKyne** [comment]
Let me know if you want to jam on the feature flags for these commands if you want to take an opportunity to simplify them @dB2510

**Comment by dB2510** [comment]
@OisinKyne sure let's get on call to discuss
