### ISSUE TITLE
Startup issue with validatorapi

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#450]
## Problem to be solved

While testing, some tests are flapping due to a race condition between instantiation of validatorapi component and eth2http service in wireValidatorMock. For example, https://github.com/ObolNetwork/charon/runs/6173470320?check_suite_focus=true

## Proposed solution

Figure out how to remove race condition between two instances. And test proposer flow for at least 1000 iterations.

**Comment by corverroos** [comment]
This has been fixed in #936
