### ISSUE TITLE
Docker image tagged with version

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#465]
## Problem to be solved

I can't find a charon image tagged with our version. Did we tag a release longer ago than when we finished the pivot to gchr?

There are also 100s of untagged docker images pushed, are we missing tags/pushing duplicate images?

https://github.com/ObolNetwork/charon/pkgs/container/charon/

## Proposed solution

Tag a version 0.3.1 and push it and verify that versions are getting properly tagged docker images. 

### Out of Scope

Cleaning up old untagged docker images.

**Comment by dB2510** [comment]
@OisinKyne we have charon image tagged to our version i.e, 0.3.0 here: https://github.com/ObolNetwork/charon/pkgs/container/charon/18856691?tag=v0.3.0 . The 100s of images that you see are the ones that are pushed on every push to main when a PR is merged. The latest commit to main gets tagged with `latest` tag.
