### ISSUE TITLE
docker: login to ghcr.io to pull public docker image 

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#574]
## Problem to be solved

Currently, in order to pull a charon docker image, for ex: `docker pull ghcr.io/obolnetwork/charon:63839f5`, one needs to login into github container registry, ie, `ghcr.io`.

## Proposed solution

Explore workaround solutions that allows pulling without logging in. Also consider pushing images to dockerhub as well.
Relevant links: [Login to ghcr.io](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry)

**Comment by 0xlax** [comment]
Just did an anonymous pull after ```docker logout  ghcr.io``` and it worked since the image is public.

**Comment by xenowits** [comment]
Thanks @0xlax for pointing it. Pulling on a fresh vm without logging in works.
