### ISSUE TITLE
dkg: command hangs if one peer drops out

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#586]
## Problem to be solved

The `charon dkg` command hangs if one peer drops out/errors after the `waitForPeers` step. This is because there are multiple steps where code waits for all peers to broadcast messages. If one peer doesn't, it just blocks and waits forever.

## Proposed solution

Implement this TODO in `charon/dkg/dkg.go:511`:
```
	// TODO(corver): This can be improved by returning a context that is
	//  cancelled as soon as the connection to a single peer is lost.
```

**Comment by dB2510** [comment]
Closed by #662 and #671
