### ISSUE TITLE
docs: update readme to reflect that block proposal is working

### ISSUE THREAD

**Issue by leolara** [ObolNetwork/charon#592]
## Problem to be solved

Currently the README says block proposal doesn't work

## Proposed solution

Update README to reflect that block proposal is working

**Comment by leolara** [comment]
@OisinKyne has asked that we do not implement this until there is a blockproposal generated by charon on a testnet that we can point to. We would need to run a cluster on Prater  for one month

**Comment by dB2510** [comment]
Closed by #803
