### ISSUE TITLE
Add observed peer latency to peer connection restored log message

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#689]
## Problem to be solved

In DKG we know how far away each peer is with an RTT logged

## Proposed solution

Add an RTT if possible to Peer Connection Restored Message

Also, change it from:
```
Peer ping recovered {"peer": "zealous-area"}
```

```
Connection restored {"peer": "zealous-area"}
```

**Comment by corverroos** [comment]
Only fixed this for `Peer ping recovered `. I can't find a `Connection restored` anymore.
