### ISSUE TITLE
refactor: rename ports

### ISSUE THREAD

**Issue by xenowits** [ObolNetwork/charon#732]
## Problem to be solved

Currently, we have the following ports:
- bootnode: 16005
- monitoring-address: 16001
- validator-api-address: 16002
- charonp2p: 16003
- discv4: 16004

## Proposed solution

Change the ports as follows:
- p2p-tcp-address: 3600 (TCP+UDP - Needs to be opened)
- validator-api-address: 3610 (TCP)
- monitoring: 3620
- p2p-udp-address: 3630 (until removed). Also, UDP Discv5 port to be removed with libp2p upgrade
- bootnode-http-address: 3640 (until removed). Also, move ENR server to monitoring server and healthchecks

**Comment by OisinKyne** [comment]
Super nit-picky change sorry 😭 

Lets make `charon-p2p` 3610, and `validatorapi` 3600, because the validatorapi is the piece every dev will have to touch but charonp2p can stay default almost always.

**Comment by xenowits** [comment]
> Super nit-picky change sorry 😭
> 
> Lets make `charon-p2p` 3610, and `validatorapi` 3600, because the validatorapi is the piece every dev will have to touch but charonp2p can stay default almost always.

raised a [PR](https://github.com/ObolNetwork/charon/pull/740)
