### ISSUE TITLE
Publish docker image to dockerhub

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#781]
## Problem to be solved

We are publishing our image to ghcr.io but that might cause authentication problems for some of our users. To solve that we need to publish our docker image to dockerhub to make it accessible to everyone.

## Proposed solution

Publish docker image to dockerhub alongwith ghcr.io. The `build-push-deploy` workflow needs to be updated. Also `charon-distributed-validator-node`, `charon-distributed-validator-cluster` and `obol-docs` repositories needs to be updated with appropriate link.

**Comment by corverroos** [comment]
Success: https://hub.docker.com/r/obolnetwork/charon/tags
