### ISSUE TITLE
Remove enr commands

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#784]
## Problem to be solved

When we execute `charon enr` command after creating `charon-enr-private-key` with `charon create enr` command, the expected behavior is to print ENR string generated at the time of executing `charon create enr` command. But it prints new ENR string every time because it takes current timestamp as parameter to create an ENR string [here](https://github.com/ethereum/go-ethereum/blob/e394d01f2a578765868355e98898bd17d3d076c1/p2p/enode/localnode.go#L84).

## Proposed solution

Use peer id which is generated from public key corresponding to libp2p secp256k1 private key as constant string in cluster artifacts. The following steps can be taken: 
- Introduce a new command as `charon create key` to move away from using enr term, which prints peer id called as identity as output.
- Introduce `charon identity` command which will output peer id.
- Do not remove `charon create enr` and `charon enr` commands following trunk based development. It can be removed after completion of athena as discussed.
- Post completion of athena update cluster artifacts to replace ENRs with identity strings.

**Comment by OisinKyne** [comment]
I'm not in a hurry to change the external API of this just yet, though I'm aligned on changing things under the hood as discussed, definitely lets have a design sync with product on this before it gets pulled into a sprint. 

Some of the reasons I want to make sure we take this slow and get right include: `create key`, and `identity` don't naturally match one another imo; and dependent on our talks about V2, we might need a different type of private key identity, e.g. a BLS pkey, so our auth/identity system might take a step up in complexity at the same time we swap things.

**Comment by corverroos** [comment]
Libp2p supports the following key types:
 - Rsa
 - Ed2551
 - Secp256k1 (`ecdsa.GenerateKey(S256(),...)`)
 - ECDSA (`ecdsa.GenerateKey(P256(),...)`)
 
 It doesn't support BLS it seems.

**Comment by corverroos** [comment]
On the API, what about grouping all identity related commands under a `identity` subcommand?

E.g.:
 - `charon identity create` Creates a private key and prints the peer.ID
 - `charon identity inspect` Prints the peer.ID from existing private key (along with private key path)

**Comment by corverroos** [comment]
btw, teku also uses peer ID instead of ENRs. They have a `peer` subcommand:
```
<img width="901" alt="image" src="https://user-images.githubusercontent.com/29249923/185057877-d99549e0-3a04-44d1-bb90-039c97034abe.png">

```

**Comment by dB2510** [comment]
this is resolved as `charon enr` command returns enr which create as part of `charon create enr`.
