### ISSUE TITLE
Duty Builder Proposer - Builder Spec Implementation

### ISSUE THREAD

**Issue by ciaranmcveigh5** [ObolNetwork/charon#809]
## Problem to be solved

Charon clusters should be compatible with the builder-specs to enable builder/proposer separation. One of the requirements for validators is the implementation of SignedBlindedBeaconBlock https://github.com/ethereum/builder-specs/blob/main/specs/builder.md#signedblindedbeaconblock.
 
## Proposed solution

A new Duty called DutyBuilderProposer, will closely follow the implementation seen in DutyProposer.

PRs
- [x]  Addition of the Duty in core/types.go
- [x] Unsigned data implementation in core/unisgneddata.go
- [x] Signed data implementation in core/signeddata.go
- [x] Validator api implementation in core/validatorapi/validatorapi.go
- [x] Scheduler implementation in core/scheduler/scheduler.go
- [x] Fetcher implementation in core/fetcher/fetcher.go
- [x] Dutydb implementation in core/dutydb/memory.go
- [x] app & cmd implementation of builder flag (not wired up)
- [x] Broadcast implementation in core/bcast/bcast.go
- [x] Protobuff implementation in core/proto.go
- [x] Interfaces implementation in core/interfaces.go
- [x] eth2types validatorapi in core/validatorapi/eth2types.go
- [x] router validatorapi in core/validatorapi/router.go
- [x] blindedbeaconblockproposalprovider in testutil/validatormock/validator mock.go 
- [x] Documentation

### Out of Scope

n/a

**Comment by corverroos** [comment]
Closing to include in v0.10.0 release notes
