### ISSUE TITLE
Duty Builder Registration - Builder Spec Implementation

### ISSUE THREAD

**Issue by ciaranmcveigh5** [ObolNetwork/charon#849]
## Problem to be solved

Charon clusters should be compatible with the builder-specs to enable builder/proposer separation. One of the requirements for validators is the implementation of SignedValidatorRegistrationV1 https://github.com/ethereum/builder-specs/blob/main/specs/builder.md#signedvalidatorregistrationv1

## Proposed solution

A new Duty called DutyBuilderRegistration will closely follow the implementation seen in DutyExit / DutyRandao.

PRs

- [x] Addition of the Duty in core/types.go
- [x] signeddata implementation
- [x] bcast implementation
- [x] validatorapi implementation
- [x] proto.go
- [x] sigagg.go
- [x] Documentation
### Out of Scope

n/a

**Comment by corverroos** [comment]
Closing to include in v0.10.0 release notes
