### ISSUE TITLE
Silence "dial backoff" warnings when relay reservations fail

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#883]
## Problem to be solved

When the bootnode isn't reachable, we are spammed with "dial backoff" warnings. These are noise, since they obscure the real reason which is only logged every 5min when the backoff code actually attempts to dial (the libp2p exponential backoff cap).

## Proposed solution

Catch and ignore "ErrDialBackoff" when reserving relay circuits.

### Out of Scope

Note we could use the p2psender log filter functionality which would result in the same thing, but its API doesn't support this.

**Comment by OisinKyne** [comment]
.... do we really only retry every 5 minutes or is that the exponential back off cap? and that it is at minimum every 5 minutes

**Comment by corverroos** [comment]
yup, libp2p default exponential backoff cap

**Comment by corverroos** [comment]
Closing this favour of #986
