### ISSUE TITLE
`charon create enr` overwrites an existing one on disk

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#893]
## Problem to be solved

I wanted to reassure people that calling `charon enr` again on the same private key will make an ENR that looks different, but has the same private key in it under the hood. While testing I ran `charon enr`, copied it into enr-viewer.com, then ran `charon create enr`, got an enr that looked different, so I put it int enr-viewer.com in another tab to assert that the public keys would be the same until  I realised they didn't match.  

Investigating further I saw that `charon create enr` seemed happy to silently overwrite an existing private key found there. 

Note, this was  with a local `go install` charon version: `v0.7.0 [git_commit_hash=dd47136,git_commit_time=2022-07-07T15:39:53Z]` so this may be fixed in later versions. 

## Proposed solution

If there is  a file at  `.charon/charon-enr-private-key` or wherever directed, log something like `charon-enr-private-key already present, using it` and generate an ENR from that, rather than creating a new one and overwriting it. 

If what's present doesn't work as a private key (can't open/read file, not an integer parsed out of it etc.) the command should fail with `Unrecognised charon-enr-private-key file present, failed to issue an ENR from it`. 

### Out of Scope

If there is anything to highlight as out of scope for this issue, please outline it here.

**Comment by xenowits** [comment]
I think that was an issue with the previous versions but not with the latest version `v0.9.0` onwards (i am confirming this with `v0.9.0 [git_commit_hash=a144a15,git_commit_time=2022-08-04T03:31:06Z]`).

**Comment by xenowits** [comment]
I'm curious as to why you had this issue since you are on `v0.7.0` but the fix was already released as part of `v0.3.0` (https://github.com/ObolNetwork/charon/releases/tag/v0.3.0).

**Comment by xenowits** [comment]
Also, the behaviour is as follows:
1. If `charon-enr-private-key` already exists, running `charon enr` DOESN'T create a new key. It simply loads the key from `.charon/charon-enr-private-key` and derives and prints the ENR from it.
2. If `charon-enr-private-key` doesn't exist, running `charon enr` outputs an error:
```
Error: private key not found. If this is your first time running this client, create one with `charon create enr`.
Usage:
  charon enr [flags]

Flags:
      --data-dir string                The directory where charon will store all its internal data (default ".charon")
  -h, --help                           Help for enr
      --p2p-allowlist string           Comma-separated list of CIDR subnets for allowing only certain peer connections. Example: 192.168.0.0/16 would permit connections to peers on your local network only. The default is to accept all connections.
      --p2p-bootnode-relay             Enables using bootnodes as libp2p circuit relays. Useful if some charon nodes are not have publicly accessible.
      --p2p-bootnodes strings          Comma-separated list of discv5 bootnode URLs or ENRs. (default [http://bootnode.gcp.obol.tech:3640/enr])
      --p2p-bootnodes-from-lockfile    Enables using cluster lock ENRs as discv5 bootnodes. Allows skipping explicit bootnodes if key generation ceremony included correct IPs.
      --p2p-denylist string            Comma-separated list of CIDR subnets for disallowing certain peer connections. Example: 192.168.0.0/16 would disallow connections to peers on your local network. The default is to accept all connections.
      --p2p-external-hostname string   The DNS hostname advertised by libp2p. This may be used to advertise an external DNS.
      --p2p-external-ip string         The IP address advertised by libp2p. This may be used to advertise an external IP.
      --p2p-tcp-address strings        Comma-separated list of listening TCP addresses (ip and port) for libP2P traffic. (default [127.0.0.1:3610])
      --p2p-udp-address string         Listening UDP address (ip and port) for discv5 discovery. (default "127.0.0.1:3630")

Error: private key not found. If this is your first time running this client, create one with `charon create enr`.
```

**Comment by xenowits** [comment]
The current behaviour for `charon create enr` is as follows:
1. If `charon-enr-private-key` already exists, it OVERWRITES the existing private key.
2. If `charon-enr-private-key` doesn't exist, it CREATES a new one.

NOTE: No warning is logged when overwriting an existing key when `charon create enr` is ran again.

**Comment by corverroos** [comment]
@xenowits just error in `charon create enr` is the file already exists.

**Comment by corverroos** [comment]
For `charon enr`, I suggest we print out the ENR as currently, BUT ALSO print out the decoded ENR. That way it is obvious why a new ENR is printed every time, but it also clear that the identity/pubkey remains the same.

Note that `charon create enr` is technically a misnomer, since it creates a private key AND a ENR. `charon enr` creates a new ENR from that existing private key... 


<img width="1416" alt="image" src="https://user-images.githubusercontent.com/29249923/182796527-1c6a7b71-cba8-4c7f-8848-06532e4ce1d6.png">

**Comment by corverroos** [comment]
Suggest also updating the `charon enr` command description.

From: `Return information on this node's Ethereum Node Record (ENR)`
To: `Prints a new generated Ethereum Node Record (ENR) from this nodes charon-enr-private-key`
