### ISSUE TITLE
Autogenerated names swapped for charon-1

### ISSUE THREAD

**Issue by thomasheremans** [ObolNetwork/charon#905]

**Comment by corverroos** [comment]
I know I suggested this, but the random deterministic names are growing on me. Also, it works well for bootnodes which are "external" to the cluster. And since clusters are long lived, names might add some nice flavour and identity and might works just as well as numbers.

**Comment by corverroos** [comment]
Seems like we are going to stick with "random deterministic names" until a bigger upgrade later where we move to "human provided names". So closing this.
