### ISSUE TITLE
Spec out endpoint changes to beacon API for sync committee, att agg. and sync agg.

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#906]
## Problem to be solved

We need to get a unit test for our proposed change to the beacon api. In particular  we have an aggregation duty proposal open, but we should also catch up on sync attestation, sync aggregation, and mev-registration at the same time 

## Proposed solution

Make a spec/basic test for what we want to implement, such that we can fork eth2-client to make the changes.

**Comment by corverroos** [comment]
Attestation Aggregation design doc: https://docs.google.com/document/d/1_J8Y9M4FsONmEENSPwzzZW9n_zrnmAPGoSO2sm6DIO8/edit#

**Comment by xenowits** [comment]
Sync committee design doc:
https://docs.google.com/document/d/1HrnW0CPuZmcGWPTQTMVQmBW8PF-2juB0WoaQHdlhySw/edit#

**Comment by corverroos** [comment]
Sync Committee Contribution design doc
https://docs.google.com/document/d/1wxfxi9cpihxqrgeewH0fnWwUxUk-HOAKw15btfd08PU/edit#
