### ISSUE TITLE
Flapy integration test

### ISSUE THREAD

**Issue by dB2510** [ObolNetwork/charon#910]
# 🐞 Bug Report

### Description

We have some integration tests that are slow, which is why they run CI builds. However, some of these tests require some condition to satisfy within a specific duration. If condition isn't satisfied in that duration the test will fail with error: 
`Condition never satisfied`.

### Has this worked before in a previous version?

We have observed this flapping of test in previous versions as well.

## 🔬 Minimal Reproduction

This is a non-deterministic test which uses assert.Eventually to trigger a condition within a specific duration and a ticker: 
https://github.com/ObolNetwork/charon/blob/d05c54def660f742ccab9554727846310975cab0/app/app_test.go#L324
We can reproduce it by running it multiple times on local system.

## 🔥 Error
https://github.com/ObolNetwork/charon/runs/7656657905?check_suite_focus=true
<pre><code>
--- FAIL: TestPingCluster (75.01s)
    --- FAIL: TestPingCluster/bootnode_and_stale_enrs (64.00s)
        app_test.go:220: 
            	Error Trace:	/home/runner/work/charon/charon/app/app_test.go:324
            	            				/home/runner/work/charon/charon/app/app_test.go:367
            	            				/home/runner/work/charon/charon/app/app_test.go:220
            	            				/home/runner/work/charon/charon/app/errgroup.go:75
            	            				/home/runner/work/charon/charon/app/asm_amd64.s:1571
            	Error:      	Condition never satisfied
            	Test:       	TestPingCluster/bootnode_and_stale_enrs
        app_test.go:111: 
            	Error Trace:	/home/runner/work/charon/charon/app/app_test.go:231
            	            				/home/runner/work/charon/charon/app/app_test.go:111
            	Error:      	Received unexpected error:
            	            	Timeout waiting for callbacks, expect=6, actual=4: map[0-1:true 1-0:true 1-2:true 2-1:true]
            	Test:       	TestPingCluster/bootnode_and_stale_enrs

</code></pre>

**Comment by corverroos** [comment]
When last did this flap?

**Comment by dB2510** [comment]
> When last did this flap?

https://github.com/ObolNetwork/charon/runs/7656657905?check_suite_focus=true
This was 14 days ago. I don't remember more latest than this.

**Comment by corverroos** [comment]
Lets close it then until we can find another occurrence
