### ISSUE TITLE
Testing auto adder

### ISSUE THREAD

**Issue by OisinKyne** [ObolNetwork/charon#914]
# 🐞 Bug Report

### Description

Github action isn't auto adding stuff to a project as it should

### Has this worked before in a previous version?

Not in this repo

## 🔬 Minimal Reproduction

`this`

## 🔥 Error

<pre><code>

</code></pre>

## 🌍  Your Environment

**Operating System:**

<pre>
  <code>

  </code>
</pre>

**What version of Charon are you running? (Which release)**

<pre>
  <code>

  </code>
</pre>

**Anything else relevant (validator index / public key)?**

**Comment by corverroos** [comment]
seems to be working
