### ISSUE TITLE
Improve error message when VC key share index doesn't match charon index

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#947]
## Problem to be solved

Charon nodes infer their peerIndex (and shareIndex) from the charon-enr-private-key at runtime and the index of that identity in the cluster definition. The VC connected to that Charon node needs to be configured with matching private-key-shares. 

The Nth keyshare needs to loaded into the Nth VC connected to the Nth charon node.

If there is mix up, and the Mth keyshare is used to query the Nth charon node, then the error `unknown public key` is returned. 

This is hard to debug.

## Proposed solution

Improve error messages such that:
 - If the pubshare submitted by the VC belongs to another index in the cluster, then return: `mismatching validator client key share index, Mth key share submitted to Nth Charon node; key_share_index=2, charon_index=1` 
 - If the pubshare submitted isn't in the lock file, then return `unknown validator client key share, not in cluster lock`

**Comment by thomasheremans** [comment]
Will need to add to FAQ as well

**Comment by xenowits** [comment]
The solution works. I connected `vc0 to node1` and `vc1 to node0` and then ran the dv cluster.

**Node0 (peerIdx 1) <-> VC1 (keyshareIdx 2)**
<img width="1456" alt="Screenshot 2023-01-08 at 11 23 22" src="https://user-images.githubusercontent.com/43061995/211182600-02ab0c32-518c-4ee9-8b54-898b14f47cd0.png">

**Node1 (peerIdx 0)  <-> VC0 (keyshareIdx 1)**
<img width="1450" alt="Screenshot 2023-01-08 at 11 23 07" src="https://user-images.githubusercontent.com/43061995/211182598-5274c7a8-ab3b-4e6f-aabf-7f19ac8d573d.png">

Are `1-indexed` field values confusing? I think it's better with 0-indexed
