### ISSUE TITLE
Tracker often detects failed duties on startup

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#983]
## Problem to be solved

There are expected race conditions on charon startup:
 - Scheduler starts at slot Y
 - The VC is backing off trying to connect to charon (since it has just started)
 - Or the VC is also just starting up (docker-compose up)
 - So the VC doesn't perform the first duty. 

This results in failed duty logging and errors and metrics even though it is expected and should be ignored as it is noise not signal.

## Proposed solution

Allow startup grace period in tracker before reporting failures/participation. Ignore all expired duties for some duration after startup, suggest duration of 2 slots.

**Comment by corverroos** [comment]
Closing as this will probably not happen in practice 🤞

**Comment by thomasheremans** [comment]
Hi @corverroos, could you please size this issue as you added it to this sprint? Thanks
