### ISSUE TITLE
Drop data-dir in favour of explicit paths

### ISSUE THREAD

**Issue by corverroos** [ObolNetwork/charon#994]
## Problem to be solved

We currently have a flag `--data-dir` which is only used to implicitly load/save the `charon-enr-private-key`. While we have explicit flags for `--lock-file` and `--definition-file`. 

Making the private key file explicit has the following benefits:
  - Allows using different filenames: e.g. bootnode-enr-private-key or any user defined name
  - Makes config more obvious, `--data-dir` implies there are other things in that folder as well...
  - Aligns with `--lock-file` and `--definition-file` which is explicitly defined

## Proposed solution

- Add a `--private-key` flag with default value `.charon/charon-enr-private-key`
- Deprecate `--data-dir` and add warning if it is populated.
- Be backwards compatible
- Add a `--simnet-validator-keys` flag that contains directory to lead private key shares, default value `.charon/validator_keys/`

**Comment by xenowits** [comment]
Note that the ticket is concerned only about `charon run` and not other subcommands.
